In [5]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('GlobalLandTemperaturesByMajorCity 2.csv')

In [7]:
df

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
0,1849-01-01,26.704,1.435,Abidjan,Côte D'Ivoire,5.63N,3.23W
1,1849-02-01,27.434,1.362,Abidjan,Côte D'Ivoire,5.63N,3.23W
2,1849-03-01,28.101,1.612,Abidjan,Côte D'Ivoire,5.63N,3.23W
3,1849-04-01,26.140,1.387,Abidjan,Côte D'Ivoire,5.63N,3.23W
4,1849-05-01,25.427,1.200,Abidjan,Côte D'Ivoire,5.63N,3.23W
5,1849-06-01,24.844,1.402,Abidjan,Côte D'Ivoire,5.63N,3.23W
6,1849-07-01,24.058,1.254,Abidjan,Côte D'Ivoire,5.63N,3.23W
7,1849-08-01,23.576,1.265,Abidjan,Côte D'Ivoire,5.63N,3.23W
8,1849-09-01,23.662,1.226,Abidjan,Côte D'Ivoire,5.63N,3.23W
9,1849-10-01,25.263,1.175,Abidjan,Côte D'Ivoire,5.63N,3.23W
10,1849-11-01,26.332,1.507,Abidjan,Côte D'Ivoire,5.63N,3.23W
11,1849-12-01,25.450,1.838,Abidjan,Côte D'Ivoire,5.63N,3.23W
12,1850-01-01,25.803,1.943,Abidjan,Côte D'Ivoire,5.63N,3.23W
13,1850-02-01,27.890,1.430,Abidjan,Côte D'Ivoire,5.63N,3.23W
14,1850-03-01,27.852,2.173,Abidjan,Côte D'Ivoire,5.63N,3.23W
15,1850-04-01,26.547,1.662,Abidjan,Côte D'Ivoire,5.63N,3.23W
16,1850-05-01,25.379,1.355,Abidjan,Côte D'Ivoire,5.63N,3.23W
17,1850-06-01,24.903,1.178,Abidjan,Côte D'Ivoire,5.63N,3.23W
18,1850-07-01,24.040,1.301,Abidjan,Côte D'Ivoire,5.63N,3.23W
19,1850-08-01,23.758,1.282,Abidjan,Côte D'Ivoire,5.63N,3.23W
20,1850-09-01,24.000,1.220,Abidjan,Côte D'Ivoire,5.63N,3.23W
21,1850-10-01,24.491,1.178,Abidjan,Côte D'Ivoire,5.63N,3.23W
22,1850-11-01,25.542,1.719,Abidjan,Côte D'Ivoire,5.63N,3.23W
23,1850-12-01,26.014,1.603,Abidjan,Côte D'Ivoire,5.63N,3.23W
24,1851-01-01,26.789,1.249,Abidjan,Côte D'Ivoire,5.63N,3.23W
25,1851-02-01,27.363,1.218,Abidjan,Côte D'Ivoire,5.63N,3.23W
26,1851-03-01,27.181,1.428,Abidjan,Côte D'Ivoire,5.63N,3.23W
27,1851-04-01,26.604,1.654,Abidjan,Côte D'Ivoire,5.63N,3.23W
28,1851-05-01,26.212,1.195,Abidjan,Côte D'Ivoire,5.63N,3.23W
29,1851-06-01,24.898,1.329,Abidjan,Côte D'Ivoire,5.63N,3.23W
...,...,...,...,...,...,...,...
239147,2011-04-01,14.876,0.363,Xian,China,34.56N,108.97E
239148,2011-05-01,18.225,0.266,Xian,China,34.56N,108.97E
239149,2011-06-01,23.879,0.533,Xian,China,34.56N,108.97E
239150,2011-07-01,24.895,0.343,Xian,China,34.56N,108.97E
239151,2011-08-01,23.069,0.301,Xian,China,34.56N,108.97E
239152,2011-09-01,16.775,0.208,Xian,China,34.56N,108.97E
239153,2011-10-01,12.587,0.294,Xian,China,34.56N,108.97E
239154,2011-11-01,7.543,0.391,Xian,China,34.56N,108.97E
239155,2011-12-01,-0.490,0.664,Xian,China,34.56N,108.97E
239156,2012-01-01,-2.416,0.568,Xian,China,34.56N,108.97E
239157,2012-02-01,0.162,0.505,Xian,China,34.56N,108.97E
239158,2012-03-01,6.430,0.249,Xian,China,34.56N,108.97E
239159,2012-04-01,14.908,0.382,Xian,China,34.56N,108.97E
239160,2012-05-01,19.041,0.372,Xian,China,34.56N,108.97E
239161,2012-06-01,22.781,1.448,Xian,China,34.56N,108.97E
239162,2012-07-01,24.646,1.750,Xian,China,34.56N,108.97E
239163,2012-08-01,23.885,0.435,Xian,China,34.56N,108.97E
239164,2012-09-01,17.028,1.405,Xian,China,34.56N,108.97E
239165,2012-10-01,12.399,0.526,Xian,China,34.56N,108.97E
239166,2012-11-01,4.736,0.519,Xian,China,34.56N,108.97E
239167,2012-12-01,-0.822,0.451,Xian,China,34.56N,108.97E
239168,2013-01-01,-1.635,0.432,Xian,China,34.56N,108.97E
239169,2013-02-01,2.362,0.558,Xian,China,34.56N,108.97E
239170,2013-03-01,10.110,0.480,Xian,China,34.56N,108.97E
239171,2013-04-01,12.563,1.823,Xian,China,34.56N,108.97E
239172,2013-05-01,18.979,0.807,Xian,China,34.56N,108.97E
239173,2013-06-01,23.522,0.647,Xian,China,34.56N,108.97E
239174,2013-07-01,25.251,1.042,Xian,China,34.56N,108.97E
239175,2013-08-01,24.528,0.840,Xian,China,34.56N,108.97E
239176,2013-09-01,NaN,NaN,Xian,China,34.56N,108.97E

In [10]:
for name, group in df.groupby('Country'):
    print name
    print group

Afghanistan
                dt  AverageTemperature  AverageTemperatureUncertainty   City  \
105635  1833-01-01               2.290                          2.487  Kabul
105636  1833-02-01               3.319                          2.325  Kabul
105637  1833-03-01               7.444                          2.733  Kabul
105638  1833-04-01              13.576                          2.266  Kabul
105639  1833-05-01              19.321                          2.362  Kabul
105640  1833-06-01              24.406                          1.972  Kabul
105641  1833-07-01              25.447                          1.620  Kabul
105642  1833-08-01              23.827                          1.778  Kabul
105643  1833-09-01              19.593                          1.749  Kabul
105644  1833-10-01              13.870                          1.762  Kabul
105645  1833-11-01              10.029                          2.016  Kabul
105646  1833-12-01               3.850                          2.369  Kabul
105647  1834-01-01              -0.106                          2.237  Kabul
105648  1834-02-01               3.369                          2.612  Kabul
105649  1834-03-01               8.918                          2.443  Kabul
105650  1834-04-01              13.462                          2.355  Kabul
105651  1834-05-01              20.039                          2.256  Kabul
105652  1834-06-01              23.652                          2.242  Kabul
105653  1834-07-01              25.760                          1.712  Kabul
105654  1834-08-01              23.964                          1.473  Kabul
105655  1834-09-01              20.347                          2.150  Kabul
105656  1834-10-01              14.314                          1.729  Kabul
105657  1834-11-01               9.276                          2.195  Kabul
105658  1834-12-01               3.979                          1.952  Kabul
105659  1835-01-01                 NaN                            NaN  Kabul
105660  1835-02-01                 NaN                            NaN  Kabul
105661  1835-03-01                 NaN                            NaN  Kabul
105662  1835-04-01                 NaN                            NaN  Kabul
105663  1835-05-01                 NaN                            NaN  Kabul
105664  1835-06-01                 NaN                            NaN  Kabul
...            ...                 ...                            ...    ...
107774  2011-04-01              15.598                          0.229  Kabul
107775  2011-05-01              24.205                          0.423  Kabul
107776  2011-06-01              27.387                          0.496  Kabul
107777  2011-07-01              26.403                          0.469  Kabul
107778  2011-08-01              25.649                          0.767  Kabul
107779  2011-09-01              22.068                          0.369  Kabul
107780  2011-10-01              15.815                          0.403  Kabul
107781  2011-11-01              10.614                          0.605  Kabul
107782  2011-12-01               3.767                          1.192  Kabul
107783  2012-01-01               0.399                          0.738  Kabul
107784  2012-02-01               1.000                          0.903  Kabul
107785  2012-03-01               8.690                          0.425  Kabul
107786  2012-04-01              15.460                          0.530  Kabul
107787  2012-05-01              20.218                          0.508  Kabul
107788  2012-06-01              25.000                          0.724  Kabul
107789  2012-07-01              27.583                          1.126  Kabul
107790  2012-08-01              25.524                          0.657  Kabul
107791  2012-09-01              21.043                          0.652  Kabul
107792  2012-10-01              15.716                          0.289  Kabul
107793  2012-11-01               9.465                          0.754  Kabul
107794  2012-12-01               4.026                          0.756  Kabul
107795  2013-01-01               2.347                          0.980  Kabul
107796  2013-02-01               4.802                          1.198  Kabul
107797  2013-03-01               8.681                          2.216  Kabul
107798  2013-04-01              14.936                          0.399  Kabul
107799  2013-05-01              21.245                          0.650  Kabul
107800  2013-06-01              25.859                          0.575  Kabul
107801  2013-07-01              26.805                          0.467  Kabul
107802  2013-08-01              24.974                          0.459  Kabul
107803  2013-09-01                 NaN                            NaN  Kabul

            Country Latitude Longitude
105635  Afghanistan   34.56N    70.05E
105636  Afghanistan   34.56N    70.05E
105637  Afghanistan   34.56N    70.05E
105638  Afghanistan   34.56N    70.05E
105639  Afghanistan   34.56N    70.05E
105640  Afghanistan   34.56N    70.05E
105641  Afghanistan   34.56N    70.05E
105642  Afghanistan   34.56N    70.05E
105643  Afghanistan   34.56N    70.05E
105644  Afghanistan   34.56N    70.05E
105645  Afghanistan   34.56N    70.05E
105646  Afghanistan   34.56N    70.05E
105647  Afghanistan   34.56N    70.05E
105648  Afghanistan   34.56N    70.05E
105649  Afghanistan   34.56N    70.05E
105650  Afghanistan   34.56N    70.05E
105651  Afghanistan   34.56N    70.05E
105652  Afghanistan   34.56N    70.05E
105653  Afghanistan   34.56N    70.05E
105654  Afghanistan   34.56N    70.05E
105655  Afghanistan   34.56N    70.05E
105656  Afghanistan   34.56N    70.05E
105657  Afghanistan   34.56N    70.05E
105658  Afghanistan   34.56N    70.05E
105659  Afghanistan   34.56N    70.05E
105660  Afghanistan   34.56N    70.05E
105661  Afghanistan   34.56N    70.05E
105662  Afghanistan   34.56N    70.05E
105663  Afghanistan   34.56N    70.05E
105664  Afghanistan   34.56N    70.05E
...             ...      ...       ...
107774  Afghanistan   34.56N    70.05E
107775  Afghanistan   34.56N    70.05E
107776  Afghanistan   34.56N    70.05E
107777  Afghanistan   34.56N    70.05E
107778  Afghanistan   34.56N    70.05E
107779  Afghanistan   34.56N    70.05E
107780  Afghanistan   34.56N    70.05E
107781  Afghanistan   34.56N    70.05E
107782  Afghanistan   34.56N    70.05E
107783  Afghanistan   34.56N    70.05E
107784  Afghanistan   34.56N    70.05E
107785  Afghanistan   34.56N    70.05E
107786  Afghanistan   34.56N    70.05E
107787  Afghanistan   34.56N    70.05E
107788  Afghanistan   34.56N    70.05E
107789  Afghanistan   34.56N    70.05E
107790  Afghanistan   34.56N    70.05E
107791  Afghanistan   34.56N    70.05E
107792  Afghanistan   34.56N    70.05E
107793  Afghanistan   34.56N    70.05E
107794  Afghanistan   34.56N    70.05E
107795  Afghanistan   34.56N    70.05E
107796  Afghanistan   34.56N    70.05E
107797  Afghanistan   34.56N    70.05E
107798  Afghanistan   34.56N    70.05E
107799  Afghanistan   34.56N    70.05E
107800  Afghanistan   34.56N    70.05E
107801  Afghanistan   34.56N    70.05E
107802  Afghanistan   34.56N    70.05E
107803  Afghanistan   34.56N    70.05E

[2169 rows x 7 columns]
Angola
                dt  AverageTemperature  AverageTemperatureUncertainty    City  \
133823  1856-01-01              24.824                          1.435  Luanda
133824  1856-02-01              24.304                          1.622  Luanda
133825  1856-03-01              24.930                          1.269  Luanda
133826  1856-04-01              24.855                          1.252  Luanda
133827  1856-05-01              23.494                          1.605  Luanda
133828  1856-06-01                 NaN                            NaN  Luanda
133829  1856-07-01                 NaN                            NaN  Luanda
133830  1856-08-01                 NaN                            NaN  Luanda
133831  1856-09-01                 NaN                            NaN  Luanda
133832  1856-10-01                 NaN                            NaN  Luanda
133833  1856-11-01                 NaN                            NaN  Luanda
133834  1856-12-01                 NaN                            NaN  Luanda
133835  1857-01-01                 NaN                            NaN  Luanda
133836  1857-02-01                 NaN                            NaN  Luanda
133837  1857-03-01                 NaN                            NaN  Luanda
133838  1857-04-01              24.028                          1.248  Luanda
133839  1857-05-01              23.057                          1.505  Luanda
133840  1857-06-01                 NaN                            NaN  Luanda
133841  1857-07-01                 NaN                            NaN  Luanda
133842  1857-08-01              19.528                          1.211  Luanda
133843  1857-09-01              21.104                          1.076  Luanda
133844  1857-10-01              22.593                          1.169  Luanda
133845  1857-11-01              23.945                          1.286  Luanda
133846  1857-12-01              24.306                          1.421  Luanda
133847  1858-01-01              24.827                          1.901  Luanda
133848  1858-02-01              24.635                          1.330  Luanda
133849  1858-03-01              25.088                          1.430  Luanda
133850  1858-04-01              25.610                          1.400  Luanda
133851  1858-05-01              23.829                          1.614  Luanda
133852  1858-06-01                 NaN                            NaN  Luanda
...            ...                 ...                            ...     ...
135686  2011-04-01              25.824                          0.497  Luanda
135687  2011-05-01              24.708                          0.919  Luanda
135688  2011-06-01              22.811                          0.992  Luanda
135689  2011-07-01              20.879                          0.373  Luanda
135690  2011-08-01              21.234                          0.883  Luanda
135691  2011-09-01              23.158                          0.547  Luanda
135692  2011-10-01              23.348                          1.177  Luanda
135693  2011-11-01              25.485                          0.580  Luanda
135694  2011-12-01              25.046                          0.584  Luanda
135695  2012-01-01              24.607                          0.705  Luanda
135696  2012-02-01              24.652                          0.719  Luanda
135697  2012-03-01              26.778                          1.683  Luanda
135698  2012-04-01              25.938                          0.704  Luanda
135699  2012-05-01              24.910                          0.563  Luanda
135700  2012-06-01              22.528                          0.712  Luanda
135701  2012-07-01              20.808                          0.686  Luanda
135702  2012-08-01              21.364                          1.022  Luanda
135703  2012-09-01              23.142                          0.546  Luanda
135704  2012-10-01              24.659                          0.408  Luanda
135705  2012-11-01              25.976                          0.753  Luanda
135706  2012-12-01              25.519                          1.289  Luanda
135707  2013-01-01              26.331                          0.754  Luanda
135708  2013-02-01              26.944                          1.034  Luanda
135709  2013-03-01              26.945                          0.588  Luanda
135710  2013-04-01              26.233                          0.979  Luanda
135711  2013-05-01              25.278                          0.867  Luanda
135712  2013-06-01              22.864                          0.624  Luanda
135713  2013-07-01              20.706                          0.470  Luanda
135714  2013-08-01              21.130                          1.169  Luanda
135715  2013-09-01                 NaN                            NaN  Luanda

       Country Latitude Longitude
133823  Angola    8.84S    13.78E
133824  Angola    8.84S    13.78E
133825  Angola    8.84S    13.78E
133826  Angola    8.84S    13.78E
133827  Angola    8.84S    13.78E
133828  Angola    8.84S    13.78E
133829  Angola    8.84S    13.78E
133830  Angola    8.84S    13.78E
133831  Angola    8.84S    13.78E
133832  Angola    8.84S    13.78E
133833  Angola    8.84S    13.78E
133834  Angola    8.84S    13.78E
133835  Angola    8.84S    13.78E
133836  Angola    8.84S    13.78E
133837  Angola    8.84S    13.78E
133838  Angola    8.84S    13.78E
133839  Angola    8.84S    13.78E
133840  Angola    8.84S    13.78E
133841  Angola    8.84S    13.78E
133842  Angola    8.84S    13.78E
133843  Angola    8.84S    13.78E
133844  Angola    8.84S    13.78E
133845  Angola    8.84S    13.78E
133846  Angola    8.84S    13.78E
133847  Angola    8.84S    13.78E
133848  Angola    8.84S    13.78E
133849  Angola    8.84S    13.78E
133850  Angola    8.84S    13.78E
133851  Angola    8.84S    13.78E
133852  Angola    8.84S    13.78E
...        ...      ...       ...
135686  Angola    8.84S    13.78E
135687  Angola    8.84S    13.78E
135688  Angola    8.84S    13.78E
135689  Angola    8.84S    13.78E
135690  Angola    8.84S    13.78E
135691  Angola    8.84S    13.78E
135692  Angola    8.84S    13.78E
135693  Angola    8.84S    13.78E
135694  Angola    8.84S    13.78E
135695  Angola    8.84S    13.78E
135696  Angola    8.84S    13.78E
135697  Angola    8.84S    13.78E
135698  Angola    8.84S    13.78E
135699  Angola    8.84S    13.78E
135700  Angola    8.84S    13.78E
135701  Angola    8.84S    13.78E
135702  Angola    8.84S    13.78E
135703  Angola    8.84S    13.78E
135704  Angola    8.84S    13.78E
135705  Angola    8.84S    13.78E
135706  Angola    8.84S    13.78E
135707  Angola    8.84S    13.78E
135708  Angola    8.84S    13.78E
135709  Angola    8.84S    13.78E
135710  Angola    8.84S    13.78E
135711  Angola    8.84S    13.78E
135712  Angola    8.84S    13.78E
135713  Angola    8.84S    13.78E
135714  Angola    8.84S    13.78E
135715  Angola    8.84S    13.78E

[1893 rows x 7 columns]
Australia
                dt  AverageTemperature  AverageTemperatureUncertainty  \
145774  1841-01-01              19.101                          4.244
145775  1841-02-01              19.744                          2.995
145776  1841-03-01              16.611                          4.420
145777  1841-04-01              12.269                          1.766
145778  1841-05-01              10.275                          1.188
145779  1841-06-01               8.550                          1.272
145780  1841-07-01               7.674                          1.970
145781  1841-08-01               8.799                          1.181
145782  1841-09-01              10.302                          1.640
145783  1841-10-01              12.436                          1.290
145784  1841-11-01              14.795                          2.033
145785  1841-12-01              16.504                          1.592
145786  1842-01-01              18.698                          1.836
145787  1842-02-01              19.461                          2.133
145788  1842-03-01              17.773                          1.891
145789  1842-04-01              12.976                          3.022
145790  1842-05-01              10.151                          1.105
145791  1842-06-01               7.946                          1.228
145792  1842-07-01               6.857                          1.016
145793  1842-08-01               8.325                          1.155
145794  1842-09-01              10.332                          1.584
145795  1842-10-01              11.144                          2.089
145796  1842-11-01              14.730                          1.346
145797  1842-12-01              17.069                          2.441
145798  1843-01-01              19.182                          1.686
145799  1843-02-01              19.978                          1.632
145800  1843-03-01              17.226                          2.064
145801  1843-04-01              12.852                          2.063
145802  1843-05-01              10.152                          1.776
145803  1843-06-01               8.788                          1.818
...            ...                 ...                            ...
218608  2011-04-01              18.067                          0.201
218609  2011-05-01              15.916                          0.148
218610  2011-06-01              15.588                          0.261
218611  2011-07-01              14.601                          0.231
218612  2011-08-01              15.571                          0.217
218613  2011-09-01              16.300                          0.132
218614  2011-10-01              16.524                          0.154
218615  2011-11-01              19.387                          0.227
218616  2011-12-01              17.318                          0.334
218617  2012-01-01              19.821                          0.293
218618  2012-02-01              19.640                          0.142
218619  2012-03-01              19.222                          0.203
218620  2012-04-01              18.695                          0.259
218621  2012-05-01              16.391                          0.186
218622  2012-06-01              15.185                          0.208
218623  2012-07-01              14.740                          0.244
218624  2012-08-01              14.892                          0.299
218625  2012-09-01              16.431                          0.272
218626  2012-10-01              16.670                          0.231
218627  2012-11-01              18.388                          0.283
218628  2012-12-01              19.617                          0.275
218629  2013-01-01              21.160                          0.263
218630  2013-02-01              20.026                          0.256
218631  2013-03-01              20.483                          0.216
218632  2013-04-01              18.547                          0.155
218633  2013-05-01              16.947                          0.154
218634  2013-06-01              15.911                          0.176
218635  2013-07-01              15.518                          0.178
218636  2013-08-01              16.126                          0.325
218637  2013-09-01                 NaN                            NaN

             City    Country Latitude Longitude
145774  Melbourne  Australia   37.78S   144.41E
145775  Melbourne  Australia   37.78S   144.41E
145776  Melbourne  Australia   37.78S   144.41E
145777  Melbourne  Australia   37.78S   144.41E
145778  Melbourne  Australia   37.78S   144.41E
145779  Melbourne  Australia   37.78S   144.41E
145780  Melbourne  Australia   37.78S   144.41E
145781  Melbourne  Australia   37.78S   144.41E
145782  Melbourne  Australia   37.78S   144.41E
145783  Melbourne  Australia   37.78S   144.41E
145784  Melbourne  Australia   37.78S   144.41E
145785  Melbourne  Australia   37.78S   144.41E
145786  Melbourne  Australia   37.78S   144.41E
145787  Melbourne  Australia   37.78S   144.41E
145788  Melbourne  Australia   37.78S   144.41E
145789  Melbourne  Australia   37.78S   144.41E
145790  Melbourne  Australia   37.78S   144.41E
145791  Melbourne  Australia   37.78S   144.41E
145792  Melbourne  Australia   37.78S   144.41E
145793  Melbourne  Australia   37.78S   144.41E
145794  Melbourne  Australia   37.78S   144.41E
145795  Melbourne  Australia   37.78S   144.41E
145796  Melbourne  Australia   37.78S   144.41E
145797  Melbourne  Australia   37.78S   144.41E
145798  Melbourne  Australia   37.78S   144.41E
145799  Melbourne  Australia   37.78S   144.41E
145800  Melbourne  Australia   37.78S   144.41E
145801  Melbourne  Australia   37.78S   144.41E

                dt  AverageTemperature  AverageTemperatureUncertainty  \
181178  1796-01-01              24.050                          2.256
181179  1796-02-01              25.371                          1.606
181180  1796-03-01              27.069                          2.168
181181  1796-04-01              29.497                          1.584
181182  1796-05-01              29.431                          1.634
181183  1796-06-01              28.073                          2.676
181184  1796-07-01              26.464                          2.026
181185  1796-08-01              27.195                          2.686
181186  1796-09-01              27.016                          3.021
181187  1796-10-01              27.042                          1.337
181188  1796-11-01              25.859                          2.589
181189  1796-12-01              22.323                          3.521
181190  1797-01-01                 NaN                            NaN
181191  1797-02-01                 NaN                            NaN
181192  1797-03-01              27.578                          1.748
181193  1797-04-01              28.546                          2.512
181194  1797-05-01              28.487                          2.143
181195  1797-06-01              28.267                          1.855
181196  1797-07-01              26.254                          1.997
181197  1797-08-01              26.851                          1.867
181198  1797-09-01              27.090                          2.713
181199  1797-10-01              26.604                          1.872
181200  1797-11-01              24.640                          1.849
181201  1797-12-01              24.158                          2.590
181202  1798-01-01              24.314                          1.835
181203  1798-02-01              25.538                          1.832
181204  1798-03-01              29.402                          1.624
181205  1798-04-01                 NaN                            NaN
181206  1798-05-01                 NaN                            NaN
181207  1798-06-01              27.689                          1.817
...            ...                 ...                            ...
183761  2011-04-01              29.866                          0.547
183762  2011-05-01              28.754                          0.447
183763  2011-06-01              27.560                          0.210
183764  2011-07-01              26.901                          0.322
183765  2011-08-01              26.726                          0.344
183766  2011-09-01              26.782                          0.430
183767  2011-10-01              27.813                          0.285
183768  2011-11-01              27.298                          0.287
183769  2011-12-01              25.716                          0.577
183770  2012-01-01              25.067                          0.275
183771  2012-02-01              27.153                          0.356
183772  2012-03-01              29.550                          0.342
183773  2012-04-01              31.398                          0.350
183774  2012-05-01              29.812                          0.612
183775  2012-06-01              28.086                          0.421
183776  2012-07-01              26.483                          2.035
183777  2012-08-01              27.026                          0.495
183778  2012-09-01              28.010                          0.356
183779  2012-10-01              28.246                          0.332
183780  2012-11-01              28.451                          0.310
183781  2012-12-01              26.148                          0.592
183782  2013-01-01              24.774                          0.628
183783  2013-02-01              27.750                          0.572
183784  2013-03-01              28.923                          1.151
183785  2013-04-01              30.780                          1.104
183786  2013-05-01              29.850                          0.794
183787  2013-06-01              27.796                          0.918
183788  2013-07-01              27.196                          0.315
183789  2013-08-01              27.236                          0.377
183790  2013-09-01                 NaN                            NaN

           City Country Latitude Longitude
181178  Rangoon   Burma   16.87N    95.44E
181179  Rangoon   Burma   16.87N    95.44E
181180  Rangoon   Burma   16.87N    95.44E
181181  Rangoon   Burma   16.87N    95.44E
181182  Rangoon   Burma   16.87N    95.44E
181183  Rangoon   Burma   16.87N    95.44E
181184  Rangoon   Burma   16.87N    95.44E
181185  Rangoon   Burma   16.87N    95.44E
181186  Rangoon   Burma   16.87N    95.44E
181187  Rangoon   Burma   16.87N    95.44E
181188  Rangoon   Burma   16.87N    95.44E
181189  Rangoon   Burma   16.87N    95.44E
181190  Rangoon   Burma   16.87N    95.44E
181191  Rangoon   Burma   16.87N    95.44E
181192  Rangoon   Burma   16.87N    95.44E
181193  Rangoon   Burma   16.87N    95.44E
181194  Rangoon   Burma   16.87N    95.44E
181195  Rangoon   Burma   16.87N    95.44E
181196  Rangoon   Burma   16.87N    95.44E
181197  Rangoon   Burma   16.87N    95.44E
181198  Rangoon   Burma   16.87N    95.44E
181199  Rangoon   Burma   16.87N    95.44E
181200  Rangoon   Burma   16.87N    95.44E
181201  Rangoon   Burma   16.87N    95.44E
181202  Rangoon   Burma   16.87N    95.44E
181203  Rangoon   Burma   16.87N    95.44E
181204  Rangoon   Burma   16.87N    95.44E
181205  Rangoon   Burma   16.87N    95.44E
181206  Rangoon   Burma   16.87N    95.44E
181207  Rangoon   Burma   16.87N    95.44E
...         ...     ...      ...       ...
183761  Rangoon   Burma   16.87N    95.44E
183762  Rangoon   Burma   16.87N    95.44E
183763  Rangoon   Burma   16.87N    95.44E
183764  Rangoon   Burma   16.87N    95.44E
183765  Rangoon   Burma   16.87N    95.44E
183766  Rangoon   Burma   16.87N    95.44E
183767  Rangoon   Burma   16.87N    95.44E
183768  Rangoon   Burma   16.87N    95.44E
183769  Rangoon   Burma   16.87N    95.44E
183770  Rangoon   Burma   16.87N    95.44E
183771  Rangoon   Burma   16.87N    95.44E
183772  Rangoon   Burma   16.87N    95.44E
183773  Rangoon   Burma   16.87N    95.44E
183774  Rangoon   Burma   16.87N    95.44E
183775  Rangoon   Burma   16.87N    95.44E
183776  Rangoon   Burma   16.87N    95.44E
183777  Rangoon   Burma   16.87N    95.44E
183778  Rangoon   Burma   16.87N    95.44E
183779  Rangoon   Burma   16.87N    95.44E
183780  Rangoon   Burma   16.87N    95.44E
183781  Rangoon   Burma   16.87N    95.44E
183782  Rangoon   Burma   16.87N    95.44E
183783  Rangoon   Burma   16.87N    95.44E
183784  Rangoon   Burma   16.87N    95.44E
183785  Rangoon   Burma   16.87N    95.44E
183786  Rangoon   Burma   16.87N    95.44E
183787  Rangoon   Burma   16.87N    95.44E
183788  Rangoon   Burma   16.87N    95.44E
183789  Rangoon   Burma   16.87N    95.44E
183790  Rangoon   Burma   16.87N    95.44E

[2613 rows x 7 columns]
Canada
                dt  AverageTemperature  AverageTemperatureUncertainty  \
151957  1743-11-01              -1.854                          1.734
151958  1743-12-01                 NaN                            NaN
151959  1744-01-01                 NaN                            NaN
151960  1744-02-01                 NaN                            NaN
151961  1744-03-01                 NaN                            NaN
151962  1744-04-01               5.164                          2.209
151963  1744-05-01              12.306                          1.541
151964  1744-06-01              18.401                          1.460
151965  1744-07-01              19.320                          1.331
151966  1744-08-01                 NaN                            NaN
151967  1744-09-01              11.273                          1.446
151968  1744-10-01               4.949                          1.564
151969  1744-11-01              -1.908                          1.511
151970  1744-12-01              -9.774                          1.828
151971  1745-01-01             -11.217                          1.850
151972  1745-02-01             -11.169                          1.710
151973  1745-03-01              -5.375                          1.581
151974  1745-04-01               3.526                          1.344
151975  1745-05-01                 NaN                            NaN
151976  1745-06-01                 NaN                            NaN
151977  1745-07-01                 NaN                            NaN
151978  1745-08-01                 NaN                            NaN
151979  1745-09-01                 NaN                            NaN
151980  1745-10-01                 NaN                            NaN
151981  1745-11-01                 NaN                            NaN
151982  1745-12-01                 NaN                            NaN
151983  1746-01-01                 NaN                            NaN
151984  1746-02-01                 NaN                            NaN
151985  1746-03-01                 NaN                            NaN
151986  1746-04-01                 NaN                            NaN
...            ...                 ...                            ...
232899  2011-04-01               5.248                          0.245
232900  2011-05-01              13.130                          0.326
232901  2011-06-01              17.216                          0.351
232902  2011-07-01              21.956                          0.246
232903  2011-08-01              20.021                          0.212
232904  2011-09-01              15.939                          0.187
232905  2011-10-01               9.385                          0.281
232906  2011-11-01               5.138                          0.167
232907  2011-12-01              -1.369                          0.268
232908  2012-01-01              -3.955                          0.349
232909  2012-02-01              -2.699                          0.254
232910  2012-03-01               5.238                          0.528
232911  2012-04-01               5.251                          0.224
232912  2012-05-01              14.946                          0.241
232913  2012-06-01              18.771                          0.285
232914  2012-07-01              21.876                          0.292
232915  2012-08-01              19.759                          0.301
232916  2012-09-01              14.955                          0.219
232917  2012-10-01               8.930                          0.140
232918  2012-11-01               1.907                          0.181
232919  2012-12-01              -1.003                          0.356
232920  2013-01-01              -4.681                          0.235
232921  2013-02-01              -6.743                          0.519
232922  2013-03-01              -1.862                          0.449
232923  2013-04-01               4.657                          0.318
232924  2013-05-01              13.818                          0.278
232925  2013-06-01              17.367                          0.226
232926  2013-07-01              20.460                          0.290
232927  2013-08-01              18.520                          0.342
232928  2013-09-01              14.599                          1.274

            City Country Latitude Longitude
151957  Montreal  Canada   45.81N    72.69W
151958  Montreal  Canada   45.81N    72.69W
151959  Montreal  Canada   45.81N    72.69W
151960  Montreal  Canada   45.81N    72.69W
151961  Montreal  Canada   45.81N    72.69W
151962  Montreal  Canada   45.81N    72.69W
151963  Montreal  Canada   45.81N    72.69W
151964  Montreal  Canada   45.81N    72.69W
151965  Montreal  Canada   45.81N    72.69W
151966  Montreal  Canada   45.81N    72.69W
151967  Montreal  Canada   45.81N    72.69W
151968  Montreal  Canada   45.81N    72.69W
151969  Montreal  Canada   45.81N    72.69W
151970  Montreal  Canada   45.81N    72.69W
151971  Montreal  Canada   45.81N    72.69W
151972  Montreal  Canada   45.81N    72.69W
151973  Montreal  Canada   45.81N    72.69W
151974  Montreal  Canada   45.81N    72.69W
151975  Montreal  Canada   45.81N    72.69W
151976  Montreal  Canada   45.81N    72.69W
151977  Montreal  Canada   45.81N    72.69W
151978  Montreal  Canada   45.81N    72.69W
151979  Montreal  Canada   45.81N    72.69W
151980  Montreal  Canada   45.81N    72.69W
151981  Montreal  Canada   45.81N    72.69W
151982  Montreal  Canada   45.81N    72.69W
151983  Montreal  Canada   45.81N    72.69W
151984  Montreal  Canada   45.81N    72.69W
151985  Montreal  Canada   45.81N    72.69W
151986  Montreal  Canada   45.81N    72.69W
...          ...     ...      ...       ...
232899   Toronto  Canada   44.20N    80.50W
232900   Toronto  Canada   44.20N    80.50W
232901   Toronto  Canada   44.20N    80.50W
232902   Toronto  Canada   44.20N    80.50W
232903   Toronto  Canada   44.20N    80.50W
232904   Toronto  Canada   44.20N    80.50W
232905   Toronto  Canada   44.20N    80.50W
232906   Toronto  Canada   44.20N    80.50W
232907   Toronto  Canada   44.20N    80.50W
232908   Toronto  Canada   44.20N    80.50W
232909   Toronto  Canada   44.20N    80.50W
232910   Toronto  Canada   44.20N    80.50W
232911   Toronto  Canada   44.20N    80.50W
232912   Toronto  Canada   44.20N    80.50W
232913   Toronto  Canada   44.20N    80.50W
232914   Toronto  Canada   44.20N    80.50W
232915   Toronto  Canada   44.20N    80.50W
232916   Toronto  Canada   44.20N    80.50W
232917   Toronto  Canada   44.20N    80.50W
232918   Toronto  Canada   44.20N    80.50W
232919   Toronto  Canada   44.20N    80.50W
232920   Toronto  Canada   44.20N    80.50W
232921   Toronto  Canada   44.20N    80.50W
232922   Toronto  Canada   44.20N    80.50W
232923   Toronto  Canada   44.20N    80.50W
232924   Toronto  Canada   44.20N    80.50W
232925   Toronto  Canada   44.20N    80.50W
232926   Toronto  Canada   44.20N    80.50W
232927   Toronto  Canada   44.20N    80.50W
232928   Toronto  Canada   44.20N    80.50W

[6478 rows x 7 columns]
Chile
                dt  AverageTemperature  AverageTemperatureUncertainty  \
198861  1855-05-01               2.379                          1.432
198862  1855-06-01              -1.743                          2.225
198863  1855-07-01              -1.833                          1.592
198864  1855-08-01               0.072                          1.391
198865  1855-09-01               1.771                          1.326
198866  1855-10-01               3.875                          1.725
198867  1855-11-01               7.661                          1.298
198868  1855-12-01               8.408                          2.704
198869  1856-01-01              12.208                          1.373
198870  1856-02-01              10.167                          1.187
198871  1856-03-01               8.200                          2.611
198872  1856-04-01               5.086                          1.915
198873  1856-05-01               0.879                          1.372
198874  1856-06-01               0.137                          1.363
198875  1856-07-01              -0.961                          1.392
198876  1856-08-01              -0.639                          1.755
198877  1856-09-01               1.477                          1.446
198878  1856-10-01               4.323                          1.213
198879  1856-11-01               8.562                          1.289
198880  1856-12-01              10.524                          1.922
198881  1857-01-01              11.917                          1.706
198882  1857-02-01              10.599                          1.471
198883  1857-03-01               9.456                          2.182
198884  1857-04-01               4.037                          2.305
198885  1857-05-01               1.595                          1.594
198886  1857-06-01               0.253                          1.928
198887  1857-07-01              -0.713                          2.280
198888  1857-08-01              -0.291                          2.180
198889  1857-09-01               1.699                          2.354
198890  1857-10-01               3.594                          2.247
...            ...                 ...                            ...
200732  2011-04-01               6.855                          0.425
200733  2011-05-01               2.652                          0.343
200734  2011-06-01              -0.609                          0.470
200735  2011-07-01              -1.692                          0.490
200736  2011-08-01               0.101                          0.290
200737  2011-09-01               4.656                          0.264
200738  2011-10-01               5.954                          0.391
200739  2011-11-01               9.987                          0.425
200740  2011-12-01              12.513                          0.393
200741  2012-01-01              13.918                          0.380
200742  2012-02-01              13.280                          0.466
200743  2012-03-01              11.758                          0.469
200744  2012-04-01               6.864                          0.445
200745  2012-05-01               4.030                          0.390
200746  2012-06-01               0.367                          0.858
200747  2012-07-01              -1.286                          0.213
200748  2012-08-01               0.890                          0.275
200749  2012-09-01               4.110                          0.444
200750  2012-10-01               5.801                          0.175
200751  2012-11-01               9.963                          0.326
200752  2012-12-01              12.129                          0.307
200753  2013-01-01              13.417                          0.237
200754  2013-02-01              13.191                          0.364
200755  2013-03-01               9.534                          0.312
200756  2013-04-01               6.862                          0.527
200757  2013-05-01               3.297                          0.365
200758  2013-06-01               0.886                          0.599
200759  2013-07-01              -0.521                          0.600
200760  2013-08-01               0.839                          0.390
200761  2013-09-01                 NaN                            NaN

            City Country Latitude Longitude
198861  Santiago   Chile   32.95S    69.89W
198862  Santiago   Chile   32.95S    69.89W
198863  Santiago   Chile   32.95S    69.89W
198864  Santiago   Chile   32.95S    69.89W
198865  Santiago   Chile   32.95S    69.89W
198866  Santiago   Chile   32.95S    69.89W
198867  Santiago   Chile   32.95S    69.89W
198868  Santiago   Chile   32.95S    69.89W
198869  Santiago   Chile   32.95S    69.89W
198870  Santiago   Chile   32.95S    69.89W
198871  Santiago   Chile   32.95S    69.89W
198872  Santiago   Chile   32.95S    69.89W
198873  Santiago   Chile   32.95S    69.89W
198874  Santiago   Chile   32.95S    69.89W
198875  Santiago   Chile   32.95S    69.89W
198876  Santiago   Chile   32.95S    69.89W
198877  Santiago   Chile   32.95S    69.89W
198878  Santiago   Chile   32.95S    69.89W
198879  Santiago   Chile   32.95S    69.89W
198880  Santiago   Chile   32.95S    69.89W
198881  Santiago   Chile   32.95S    69.89W
198882  Santiago   Chile   32.95S    69.89W
198883  Santiago   Chile   32.95S    69.89W
198884  Santiago   Chile   32.95S    69.89W
198885  Santiago   Chile   32.95S    69.89W
198886  Santiago   Chile   32.95S    69.89W
198887  Santiago   Chile   32.95S    69.89W
198888  Santiago   Chile   32.95S    69.89W
198889  Santiago   Chile   32.95S    69.89W
198890  Santiago   Chile   32.95S    69.89W
...          ...     ...      ...       ...
200732  Santiago   Chile   32.95S    69.89W
200733  Santiago   Chile   32.95S    69.89W

               dt  AverageTemperature  AverageTemperatureUncertainty  \
9224   1791-05-01              20.772                          1.848
9225   1791-06-01              24.029                          1.945
9226   1791-07-01              25.483                          1.479
9227   1791-08-01              26.797                          1.435
9228   1791-09-01              24.464                          1.987
9229   1791-10-01              21.999                          1.919
9230   1791-11-01              20.984                          1.815
9231   1791-12-01              16.251                          1.835
9232   1792-01-01              12.512                          3.428
9233   1792-02-01              15.282                          2.847
9234   1792-03-01              15.695                          2.266
9235   1792-04-01              17.887                          2.051
9236   1792-05-01              21.686                          1.686
9237   1792-06-01              25.326                          1.559
9238   1792-07-01              25.977                          1.566
9239   1792-08-01              24.861                          1.641
9240   1792-09-01              26.075                          2.379
9241   1792-10-01              22.026                          1.953
9242   1792-11-01              19.025                          2.490
9243   1792-12-01              15.639                          2.567
9244   1793-01-01              12.307                          3.011
9245   1793-02-01              15.432                          3.843
9246   1793-03-01              15.550                          3.088
9247   1793-04-01              18.173                          2.242
9248   1793-05-01              20.799                          1.699
9249   1793-06-01              23.774                          2.221
9250   1793-07-01              25.663                          2.840
9251   1793-08-01              25.624                          2.706
9252   1793-09-01              26.084                          2.042
9253   1793-10-01              22.165                          2.743
...           ...                 ...                            ...
77086  2011-04-01              21.453                          0.276
77087  2011-05-01              25.388                          0.204
77088  2011-06-01              27.659                          0.264
77089  2011-07-01              29.582                          0.188
77090  2011-08-01              28.790                          0.377
77091  2011-09-01              27.407                          0.212
77092  2011-10-01              23.440                          0.297
77093  2011-11-01              17.498                          0.253
77094  2011-12-01              14.591                          0.487
77095  2012-01-01              12.382                          0.466
77096  2012-02-01              13.955                          0.443
77097  2012-03-01              16.461                          0.346
77098  2012-04-01              22.612                          0.160
77099  2012-05-01              26.428                          0.260
77100  2012-06-01              28.905                          0.338
77101  2012-07-01              30.263                          0.630
77102  2012-08-01              29.799                          0.615
77103  2012-09-01              27.467                          0.391
77104  2012-10-01              25.086                          0.326
77105  2012-11-01              20.931                          0.510
77106  2012-12-01              15.522                          0.292
77107  2013-01-01              14.187                          0.259
77108  2013-02-01              15.931                          0.460
77109  2013-03-01              19.695                          0.253
77110  2013-04-01              21.146                          0.477
77111  2013-05-01              27.100                          0.254
77112  2013-06-01              28.392                          0.482
77113  2013-07-01              28.217                          0.874
77114  2013-08-01              28.588                          0.750
77115  2013-09-01                 NaN                            NaN

             City Country Latitude Longitude
9224   Alexandria   Egypt   31.35N    30.16E
9225   Alexandria   Egypt   31.35N    30.16E
9226   Alexandria   Egypt   31.35N    30.16E
9227   Alexandria   Egypt   31.35N    30.16E
9228   Alexandria   Egypt   31.35N    30.16E
9229   Alexandria   Egypt   31.35N    30.16E
9230   Alexandria   Egypt   31.35N    30.16E
9231   Alexandria   Egypt   31.35N    30.16E
9232   Alexandria   Egypt   31.35N    30.16E
9233   Alexandria   Egypt   31.35N    30.16E
9234   Alexandria   Egypt   31.35N    30.16E
9235   Alexandria   Egypt   31.35N    30.16E
9236   Alexandria   Egypt   31.35N    30.16E
9237   Alexandria   Egypt   31.35N    30.16E
9238   Alexandria   Egypt   31.35N    30.16E
9239   Alexandria   Egypt   31.35N    30.16E
9240   Alexandria   Egypt   31.35N    30.16E
9241   Alexandria   Egypt   31.35N    30.16E
9242   Alexandria   Egypt   31.35N    30.16E
9243   Alexandria   Egypt   31.35N    30.16E
9244   Alexandria   Egypt   31.35N    30.16E
9245   Alexandria   Egypt   31.35N    30.16E
9246   Alexandria   Egypt   31.35N    30.16E
9247   Alexandria   Egypt   31.35N    30.16E
9248   Alexandria   Egypt   31.35N    30.16E
9249   Alexandria   Egypt   31.35N    30.16E
9250   Alexandria   Egypt   31.35N    30.16E
9251   Alexandria   Egypt   31.35N    30.16E
9252   Alexandria   Egypt   31.35N    30.16E
9253   Alexandria   Egypt   31.35N    30.16E
...           ...     ...      ...       ...
77086       Gizeh   Egypt   29.74N    31.38E
77087       Gizeh   Egypt   29.74N    31.38E
77088       Gizeh   Egypt   29.74N    31.38E
77089       Gizeh   Egypt   29.74N    31.38E
77090       Gizeh   Egypt   29.74N    31.38E
77091       Gizeh   Egypt   29.74N    31.38E
77092       Gizeh   Egypt   29.74N    31.38E
77093       Gizeh   Egypt   29.74N    31.38E
77094       Gizeh   Egypt   29.74N    31.38E
77095       Gizeh   Egypt   29.74N    31.38E
77096       Gizeh   Egypt   29.74N    31.38E
77097       Gizeh   Egypt   29.74N    31.38E
77098       Gizeh   Egypt   29.74N    31.38E
77099       Gizeh   Egypt   29.74N    31.38E
77100       Gizeh   Egypt   29.74N    31.38E
77101       Gizeh   Egypt   29.74N    31.38E
77102       Gizeh   Egypt   29.74N    31.38E
77103       Gizeh   Egypt   29.74N    31.38E
77104       Gizeh   Egypt   29.74N    31.38E
77105       Gizeh   Egypt   29.74N    31.38E
77106       Gizeh   Egypt   29.74N    31.38E
77107       Gizeh   Egypt   29.74N    31.38E
77108       Gizeh   Egypt   29.74N    31.38E
77109       Gizeh   Egypt   29.74N    31.38E
77110       Gizeh   Egypt   29.74N    31.38E
77111       Gizeh   Egypt   29.74N    31.38E
77112       Gizeh   Egypt   29.74N    31.38E
77113       Gizeh   Egypt   29.74N    31.38E
77114       Gizeh   Egypt   29.74N    31.38E
77115       Gizeh   Egypt   29.74N    31.38E

[7589 rows x 7 columns]
Ethiopia
              dt  AverageTemperature  AverageTemperatureUncertainty  \
1977  1850-01-01              15.986                          1.537
1978  1850-02-01              18.345                          1.527
1979  1850-03-01              18.632                          2.162
1980  1850-04-01              18.154                          1.693
1981  1850-05-01              17.480                          1.237
1982  1850-06-01              17.183                          1.252
1983  1850-07-01              16.449                          1.265
1984  1850-08-01              16.358                          1.232
1985  1850-09-01              16.184                          1.200
1986  1850-10-01              15.616                          1.331
1987  1850-11-01              15.126                          1.573
1988  1850-12-01                 NaN                            NaN
1989  1851-01-01                 NaN                            NaN
1990  1851-02-01                 NaN                            NaN
1991  1851-03-01                 NaN                            NaN
1992  1851-04-01                 NaN                            NaN
1993  1851-05-01                 NaN                            NaN
1994  1851-06-01                 NaN                            NaN
1995  1851-07-01                 NaN                            NaN
1996  1851-08-01                 NaN                            NaN
1997  1851-09-01                 NaN                            NaN
1998  1851-10-01                 NaN                            NaN
1999  1851-11-01                 NaN                            NaN
2000  1851-12-01                 NaN                            NaN
2001  1852-01-01                 NaN                            NaN
2002  1852-02-01                 NaN                            NaN
2003  1852-03-01                 NaN                            NaN
2004  1852-04-01                 NaN                            NaN
2005  1852-05-01                 NaN                            NaN
2006  1852-06-01                 NaN                            NaN
...          ...                 ...                            ...
3912  2011-04-01              21.223                          0.695
3913  2011-05-01              19.884                          0.525
3914  2011-06-01              18.805                          0.574
3915  2011-07-01              17.983                          2.253
3916  2011-08-01              17.571                          1.024
3917  2011-09-01              17.822                          1.028
3918  2011-10-01              17.158                          0.477
3919  2011-11-01              17.869                          1.323
3920  2011-12-01              17.486                          1.164
3921  2012-01-01              16.620                          3.478
3922  2012-02-01              18.851                          0.929
3923  2012-03-01              18.337                          2.936
3924  2012-04-01              19.228                          1.807
3925  2012-05-01              19.411                          1.326
3926  2012-06-01              20.427                          3.028
3927  2012-07-01              18.303                          2.523
3928  2012-08-01              18.927                          2.087
3929  2012-09-01              18.038                          0.673
3930  2012-10-01              17.846                          0.779
3931  2012-11-01              17.587                          1.734
3932  2012-12-01              17.808                          1.019
3933  2013-01-01              18.852                          0.998
3934  2013-02-01              20.047                          0.807
3935  2013-03-01              21.180                          0.740
3936  2013-04-01              20.570                          1.298
3937  2013-05-01              19.774                          0.720
3938  2013-06-01              18.736                          0.595
3939  2013-07-01              18.148                          1.500
3940  2013-08-01              19.005                          3.621
3941  2013-09-01                 NaN                            NaN

             City   Country Latitude Longitude
1977  Addis Abeba  Ethiopia    8.84N    38.11E
1978  Addis Abeba  Ethiopia    8.84N    38.11E
1979  Addis Abeba  Ethiopia    8.84N    38.11E
1980  Addis Abeba  Ethiopia    8.84N    38.11E
1981  Addis Abeba  Ethiopia    8.84N    38.11E
1982  Addis Abeba  Ethiopia    8.84N    38.11E
1983  Addis Abeba  Ethiopia    8.84N    38.11E
1984  Addis Abeba  Ethiopia    8.84N    38.11E
1985  Addis Abeba  Ethiopia    8.84N    38.11E
1986  Addis Abeba  Ethiopia    8.84N    38.11E
1987  Addis Abeba  Ethiopia    8.84N    38.11E
1988  Addis Abeba  Ethiopia    8.84N    38.11E
1989  Addis Abeba  Ethiopia    8.84N    38.11E
1990  Addis Abeba  Ethiopia    8.84N    38.11E
1991  Addis Abeba  Ethiopia    8.84N    38.11E
1992  Addis Abeba  Ethiopia    8.84N    38.11E
1993  Addis Abeba  Ethiopia    8.84N    38.11E
1994  Addis Abeba  Ethiopia    8.84N    38.11E
1995  Addis Abeba  Ethiopia    8.84N    38.11E
1996  Addis Abeba  Ethiopia    8.84N    38.11E
1997  Addis Abeba  Ethiopia    8.84N    38.11E
1998  Addis Abeba  Ethiopia    8.84N    38.11E
1999  Addis Abeba  Ethiopia    8.84N    38.11E
2000  Addis Abeba  Ethiopia    8.84N    38.11E
2001  Addis Abeba  Ethiopia    8.84N    38.11E
2002  Addis Abeba  Ethiopia    8.84N    38.11E
2003  Addis Abeba  Ethiopia    8.84N    38.11E
2004  Addis Abeba  Ethiopia    8.84N    38.11E
2005  Addis Abeba  Ethiopia    8.84N    38.11E
2006  Addis Abeba  Ethiopia    8.84N    38.11E
...           ...       ...      ...       ...
3912  Addis Abeba  Ethiopia    8.84N    38.11E
3913  Addis Abeba  Ethiopia    8.84N    38.11E
3914  Addis Abeba  Ethiopia    8.84N    38.11E
3915  Addis Abeba  Ethiopia    8.84N    38.11E
3916  Addis Abeba  Ethiopia    8.84N    38.11E
3917  Addis Abeba  Ethiopia    8.84N    38.11E
3918  Addis Abeba  Ethiopia    8.84N    38.11E
3919  Addis Abeba  Ethiopia    8.84N    38.11E
3920  Addis Abeba  Ethiopia    8.84N    38.11E
3921  Addis Abeba  Ethiopia    8.84N    38.11E
3922  Addis Abeba  Ethiopia    8.84N    38.11E
3923  Addis Abeba  Ethiopia    8.84N    38.11E
3924  Addis Abeba  Ethiopia    8.84N    38.11E
3925  Addis Abeba  Ethiopia    8.84N    38.11E
3926  Addis Abeba  Ethiopia    8.84N    38.11E
3927  Addis Abeba  Ethiopia    8.84N    38.11E
3928  Addis Abeba  Ethiopia    8.84N    38.11E
3929  Addis Abeba  Ethiopia    8.84N    38.11E
3930  Addis Abeba  Ethiopia    8.84N    38.11E
3931  Addis Abeba  Ethiopia    8.84N    38.11E
3932  Addis Abeba  Ethiopia    8.84N    38.11E
3933  Addis Abeba  Ethiopia    8.84N    38.11E
3934  Addis Abeba  Ethiopia    8.84N    38.11E
3935  Addis Abeba  Ethiopia    8.84N    38.11E
3936  Addis Abeba  Ethiopia    8.84N    38.11E
3937  Addis Abeba  Ethiopia    8.84N    38.11E
3938  Addis Abeba  Ethiopia    8.84N    38.11E
3939  Addis Abeba  Ethiopia    8.84N    38.11E
3940  Addis Abeba  Ethiopia    8.84N    38.11E
3941  Addis Abeba  Ethiopia    8.84N    38.11E

[1965 rows x 7 columns]
France
                dt  AverageTemperature  AverageTemperatureUncertainty   City  \
173008  1743-11-01               7.648                          1.749  Paris
173009  1743-12-01                 NaN                            NaN  Paris
173010  1744-01-01                 NaN                            NaN  Paris
173011  1744-02-01                 NaN                            NaN  Paris
173012  1744-03-01                 NaN                            NaN  Paris
173013  1744-04-01              10.195                          2.282  Paris
173014  1744-05-01              12.607                          1.553  Paris
173015  1744-06-01              16.121                          1.529  Paris
173016  1744-07-01              17.669                          1.687  Paris
173017  1744-08-01                 NaN                            NaN  Paris
173018  1744-09-01              14.375                          1.681  Paris
173019  1744-10-01              10.487                          1.657  Paris
173020  1744-11-01               6.762                          1.576  Paris
173021  1744-12-01               3.622                          1.878  Paris
173022  1745-01-01               1.955                          1.940  Paris
173023  1745-02-01               2.516                          1.762  Paris
173024  1745-03-01               5.212                          1.434  Paris
173025  1745-04-01               9.233                          1.436  Paris
173026  1745-05-01                 NaN                            NaN  Paris
173027  1745-06-01                 NaN                            NaN  Paris
173028  1745-07-01                 NaN                            NaN  Paris
173029  1745-08-01                 NaN                            NaN  Paris
173030  1745-09-01                 NaN                            NaN  Paris
173031  1745-10-01                 NaN                            NaN  Paris
173032  1745-11-01                 NaN                            NaN  Paris
173033  1745-12-01                 NaN                            NaN  Paris
173034  1746-01-01                 NaN                            NaN  Paris
173035  1746-02-01                 NaN                            NaN  Paris
173036  1746-03-01                 NaN                            NaN  Paris
173037  1746-04-01                 NaN                            NaN  Paris
...            ...                 ...                            ...    ...
176217  2011-04-01              13.959                          0.259  Paris
176218  2011-05-01              15.574                          0.365  Paris
176219  2011-06-01              17.519                          0.273  Paris
176220  2011-07-01              17.232                          0.219  Paris
176221  2011-08-01              18.630                          0.207  Paris
176222  2011-09-01              17.369                          0.270  Paris
176223  2011-10-01              12.605                          0.243  Paris
176224  2011-11-01               8.937                          0.222  Paris
176225  2011-12-01               6.955                          0.299  Paris
176226  2012-01-01               5.867                          0.257  Paris
176227  2012-02-01               1.422                          0.268  Paris
176228  2012-03-01               9.721                          0.339  Paris
176229  2012-04-01               8.781                          0.184  Paris
176230  2012-05-01              14.860                          0.237  Paris
176231  2012-06-01              15.717                          0.421  Paris
176232  2012-07-01              18.193                          0.275  Paris
176233  2012-08-01              20.103                          0.522  Paris
176234  2012-09-01              15.349                          0.354  Paris
176235  2012-10-01              11.613                          0.311  Paris
176236  2012-11-01               7.420                          0.240  Paris
176237  2012-12-01               5.593                          0.461  Paris
176238  2013-01-01               3.044                          0.746  Paris
176239  2013-02-01               2.456                          0.282  Paris
176240  2013-03-01               4.570                          0.337  Paris
176241  2013-04-01               9.559                          0.251  Paris
176242  2013-05-01              11.703                          0.282  Paris
176243  2013-06-01              16.340                          0.271  Paris
176244  2013-07-01              21.186                          0.381  Paris
176245  2013-08-01              19.235                          0.399  Paris
176246  2013-09-01                 NaN                            NaN  Paris

       Country Latitude Longitude
173008  France   49.03N     2.45E
173009  France   49.03N     2.45E
173010  France   49.03N     2.45E
173011  France   49.03N     2.45E
173012  France   49.03N     2.45E
173013  France   49.03N     2.45E
173014  France   49.03N     2.45E
173015  France   49.03N     2.45E
173016  France   49.03N     2.45E
173017  France   49.03N     2.45E
173018  France   49.03N     2.45E
173019  France   49.03N     2.45E
173020  France   49.03N     2.45E
173021  France   49.03N     2.45E
173022  France   49.03N     2.45E
173023  France   49.03N     2.45E
173024  France   49.03N     2.45E
173025  France   49.03N     2.45E
173026  France   49.03N     2.45E
173027  France   49.03N     2.45E
173028  France   49.03N     2.45E
173029  France   49.03N     2.45E
173030  France   49.03N     2.45E
173031  France   49.03N     2.45E
173032  France   49.03N     2.45E
173033  France   49.03N     2.45E

               dt  AverageTemperature  AverageTemperatureUncertainty     City  \
14998  1819-01-01               7.962                          2.870  Baghdad
14999  1819-02-01              10.974                          2.966  Baghdad
15000  1819-03-01              14.239                          4.436  Baghdad
15001  1819-04-01              20.633                          1.936  Baghdad
15002  1819-05-01                 NaN                            NaN  Baghdad
15003  1819-06-01              30.674                          2.876  Baghdad
15004  1819-07-01              32.812                          1.977  Baghdad
15005  1819-08-01              32.464                          2.039  Baghdad
15006  1819-09-01                 NaN                            NaN  Baghdad
15007  1819-10-01                 NaN                            NaN  Baghdad
15008  1819-11-01                 NaN                            NaN  Baghdad
15009  1819-12-01              11.292                          2.992  Baghdad
15010  1820-01-01                 NaN                            NaN  Baghdad
15011  1820-02-01                 NaN                            NaN  Baghdad
15012  1820-03-01              15.681                          3.494  Baghdad
15013  1820-04-01              22.100                          1.734  Baghdad
15014  1820-05-01                 NaN                            NaN  Baghdad
15015  1820-06-01                 NaN                            NaN  Baghdad
15016  1820-07-01              33.628                          1.964  Baghdad
15017  1820-08-01              31.902                          1.686  Baghdad
15018  1820-09-01                 NaN                            NaN  Baghdad
15019  1820-10-01              21.348                          3.014  Baghdad
15020  1820-11-01              15.659                          1.920  Baghdad
15021  1820-12-01              10.731                          3.745  Baghdad
15022  1821-01-01                 NaN                            NaN  Baghdad
15023  1821-02-01              12.986                          4.397  Baghdad
15024  1821-03-01              17.027                          2.370  Baghdad
15025  1821-04-01                 NaN                            NaN  Baghdad
15026  1821-05-01                 NaN                            NaN  Baghdad
15027  1821-06-01              31.040                          3.700  Baghdad
...           ...                 ...                            ...      ...
17305  2011-04-01              23.178                          0.264  Baghdad
17306  2011-05-01              29.493                          0.296  Baghdad
17307  2011-06-01              34.736                          0.321  Baghdad
17308  2011-07-01              37.184                          0.173  Baghdad
17309  2011-08-01              36.151                          0.287  Baghdad
17310  2011-09-01              32.055                          0.196  Baghdad
17311  2011-10-01              24.179                          0.434  Baghdad
17312  2011-11-01              14.241                          0.376  Baghdad
17313  2011-12-01              10.369                          0.279  Baghdad
17314  2012-01-01               9.664                          0.327  Baghdad
17315  2012-02-01              11.571                          0.344  Baghdad
17316  2012-03-01              15.376                          0.232  Baghdad
17317  2012-04-01              24.659                          0.347  Baghdad
17318  2012-05-01              30.878                          0.369  Baghdad
17319  2012-06-01              35.726                          0.384  Baghdad
17320  2012-07-01              37.371                          0.356  Baghdad
17321  2012-08-01              36.559                          0.600  Baghdad
17322  2012-09-01              32.574                          0.400  Baghdad
17323  2012-10-01              26.319                          0.664  Baghdad
17324  2012-11-01              18.590                          0.254  Baghdad
17325  2012-12-01              12.851                          0.410  Baghdad
17326  2013-01-01              11.518                          1.052  Baghdad
17327  2013-02-01              14.889                          0.809  Baghdad
17328  2013-03-01              17.636                          0.866  Baghdad
17329  2013-04-01              22.769                          1.619  Baghdad
17330  2013-05-01              28.673                          0.724  Baghdad
17331  2013-06-01              33.803                          0.836  Baghdad
17332  2013-07-01              36.392                          1.021  Baghdad
17333  2013-08-01              35.463                          0.608  Baghdad
17334  2013-09-01                 NaN                            NaN  Baghdad

      Country Latitude Longitude
14998    Iraq   32.95N    45.00E
14999    Iraq   32.95N    45.00E
15000    Iraq   32.95N    45.00E
15001    Iraq   32.95N    45.00E
15002    Iraq   32.95N    45.00E
15003    Iraq   32.95N    45.00E
15004    Iraq   32.95N    45.00E
15005    Iraq   32.95N    45.00E
15006    Iraq   32.95N    45.00E
15007    Iraq   32.95N    45.00E
15008    Iraq   32.95N    45.00E
15009    Iraq   32.95N    45.00E
15010    Iraq   32.95N    45.00E
15011    Iraq   32.95N    45.00E
15012    Iraq   32.95N    45.00E
15013    Iraq   32.95N    45.00E
15014    Iraq   32.95N    45.00E
15015    Iraq   32.95N    45.00E
15016    Iraq   32.95N    45.00E
15017    Iraq   32.95N    45.00E
15018    Iraq   32.95N    45.00E
15019    Iraq   32.95N    45.00E
15020    Iraq   32.95N    45.00E
15021    Iraq   32.95N    45.00E
15022    Iraq   32.95N    45.00E
15023    Iraq   32.95N    45.00E
15024    Iraq   32.95N    45.00E
15025    Iraq   32.95N    45.00E
15026    Iraq   32.95N    45.00E
15027    Iraq   32.95N    45.00E
...       ...      ...       ...
17305    Iraq   32.95N    45.00E
17306    Iraq   32.95N    45.00E
17307    Iraq   32.95N    45.00E
17308    Iraq   32.95N    45.00E
17309    Iraq   32.95N    45.00E
17310    Iraq   32.95N    45.00E
17311    Iraq   32.95N    45.00E
17312    Iraq   32.95N    45.00E
17313    Iraq   32.95N    45.00E
17314    Iraq   32.95N    45.00E
17315    Iraq   32.95N    45.00E
17316    Iraq   32.95N    45.00E
17317    Iraq   32.95N    45.00E
17318    Iraq   32.95N    45.00E
17319    Iraq   32.95N    45.00E
17320    Iraq   32.95N    45.00E
17321    Iraq   32.95N    45.00E
17322    Iraq   32.95N    45.00E
17323    Iraq   32.95N    45.00E
17324    Iraq   32.95N    45.00E
17325    Iraq   32.95N    45.00E
17326    Iraq   32.95N    45.00E
17327    Iraq   32.95N    45.00E
17328    Iraq   32.95N    45.00E
17329    Iraq   32.95N    45.00E
17330    Iraq   32.95N    45.00E
17331    Iraq   32.95N    45.00E
17332    Iraq   32.95N    45.00E
17333    Iraq   32.95N    45.00E
17334    Iraq   32.95N    45.00E

[2337 rows x 7 columns]
Italy
                dt  AverageTemperature  AverageTemperatureUncertainty  City  \
188021  1743-11-01               8.248                          1.917  Rome
188022  1743-12-01                 NaN                            NaN  Rome
188023  1744-01-01                 NaN                            NaN  Rome
188024  1744-02-01                 NaN                            NaN  Rome
188025  1744-03-01                 NaN                            NaN  Rome
188026  1744-04-01              12.154                          2.006  Rome
188027  1744-05-01              13.667                          1.816  Rome
188028  1744-06-01              18.179                          1.730  Rome
188029  1744-07-01              21.030                          1.710  Rome
188030  1744-08-01                 NaN                            NaN  Rome
188031  1744-09-01              17.004                          1.824  Rome
188032  1744-10-01              12.053                          1.856  Rome
188033  1744-11-01               8.017                          1.804  Rome
188034  1744-12-01               4.043                          1.979  Rome
188035  1745-01-01               1.583                          2.056  Rome
188036  1745-02-01               3.379                          1.920  Rome
188037  1745-03-01               5.606                          1.700  Rome
188038  1745-04-01              10.041                          1.651  Rome
188039  1745-05-01                 NaN                            NaN  Rome
188040  1745-06-01                 NaN                            NaN  Rome
188041  1745-07-01                 NaN                            NaN  Rome
188042  1745-08-01                 NaN                            NaN  Rome
188043  1745-09-01                 NaN                            NaN  Rome
188044  1745-10-01                 NaN                            NaN  Rome
188045  1745-11-01                 NaN                            NaN  Rome
188046  1745-12-01                 NaN                            NaN  Rome
188047  1746-01-01                 NaN                            NaN  Rome
188048  1746-02-01                 NaN                            NaN  Rome
188049  1746-03-01                 NaN                            NaN  Rome
188050  1746-04-01                 NaN                            NaN  Rome
...            ...                 ...                            ...   ...
191230  2011-04-01              12.654                          0.425  Rome
191231  2011-05-01              16.595                          0.405  Rome
191232  2011-06-01              20.723                          0.416  Rome
191233  2011-07-01              21.950                          0.276  Rome
191234  2011-08-01              23.874                          0.317  Rome
191235  2011-09-01              20.989                          0.355  Rome
191236  2011-10-01              13.463                          0.317  Rome
191237  2011-11-01               8.633                          0.646  Rome
191238  2011-12-01               5.893                          0.553  Rome
191239  2012-01-01               3.618                          0.491  Rome
191240  2012-02-01               1.802                          0.326  Rome
191241  2012-03-01              10.320                          0.609  Rome
191242  2012-04-01              11.517                          0.457  Rome
191243  2012-05-01              15.321                          0.464  Rome
191244  2012-06-01              21.560                          0.684  Rome
191245  2012-07-01              24.480                          0.476  Rome
191246  2012-08-01              24.731                          0.559  Rome
191247  2012-09-01              18.922                          0.347  Rome
191248  2012-10-01              14.501                          0.510  Rome
191249  2012-11-01              10.528                          0.333  Rome
191250  2012-12-01               4.150                          0.498  Rome
191251  2013-01-01               4.261                          0.308  Rome
191252  2013-02-01               3.577                          0.350  Rome
191253  2013-03-01               7.458                          0.532  Rome
191254  2013-04-01              12.394                          0.331  Rome
191255  2013-05-01              14.863                          0.407  Rome
191256  2013-06-01              19.338                          0.482  Rome
191257  2013-07-01              23.375                          0.598  Rome
191258  2013-08-01              23.556                          0.682  Rome
191259  2013-09-01                 NaN                            NaN  Rome

       Country Latitude Longitude
188021   Italy   42.59N    13.09E
188022   Italy   42.59N    13.09E
188023   Italy   42.59N    13.09E
188024   Italy   42.59N    13.09E
188025   Italy   42.59N    13.09E
188026   Italy   42.59N    13.09E
188027   Italy   42.59N    13.09E
188028   Italy   42.59N    13.09E
188029   Italy   42.59N    13.09E
188030   Italy   42.59N    13.09E
188031   Italy   42.59N    13.09E
188032   Italy   42.59N    13.09E
188033   Italy   42.59N    13.09E
188034   Italy   42.59N    13.09E
188035   Italy   42.59N    13.09E
188036   Italy   42.59N    13.09E
188037   Italy   42.59N    13.09E
188038   Italy   42.59N    13.09E
188039   Italy   42.59N    13.09E
188040   Italy   42.59N    13.09E
188041   Italy   42.59N    13.09E
188042   Italy   42.59N    13.09E
188043   Italy   42.59N    13.09E
188044   Italy   42.59N    13.09E
188045   Italy   42.59N    13.09E
188046   Italy   42.59N    13.09E
188047   Italy   42.59N    13.09E
188048   Italy   42.59N    13.09E
188049   Italy   42.59N    13.09E
188050   Italy   42.59N    13.09E
...        ...      ...       ...
191230   Italy   42.59N    13.09E
191231   Italy   42.59N    13.09E
191232   Italy   42.59N    13.09E
191233   Italy   42.59N    13.09E
191234   Italy   42.59N    13.09E
191235   Italy   42.59N    13.09E
191236   Italy   42.59N    13.09E
191237   Italy   42.59N    13.09E
191238   Italy   42.59N    13.09E
191239   Italy   42.59N    13.09E
191240   Italy   42.59N    13.09E
191241   Italy   42.59N    13.09E
191242   Italy   42.59N    13.09E
191243   Italy   42.59N    13.09E
191244   Italy   42.59N    13.09E
191245   Italy   42.59N    13.09E
191246   Italy   42.59N    13.09E
191247   Italy   42.59N    13.09E
191248   Italy   42.59N    13.09E
191249   Italy   42.59N    13.09E
191250   Italy   42.59N    13.09E
191251   Italy   42.59N    13.09E
191252   Italy   42.59N    13.09E
191253   Italy   42.59N    13.09E
191254   Italy   42.59N    13.09E
191255   Italy   42.59N    13.09E
191256   Italy   42.59N    13.09E
191257   Italy   42.59N    13.09E
191258   Italy   42.59N    13.09E
191259   Italy   42.59N    13.09E

[3239 rows x 7 columns]
Japan
                dt  AverageTemperature  AverageTemperatureUncertainty    City  \
158435  1841-04-01              11.223                          2.037  Nagoya
158436  1841-05-01              16.572                          1.488  Nagoya
158437  1841-06-01                 NaN                            NaN  Nagoya
158438  1841-07-01                 NaN                            NaN  Nagoya
158439  1841-08-01                 NaN                            NaN  Nagoya
158440  1841-09-01                 NaN                            NaN  Nagoya
158441  1841-10-01                 NaN                            NaN  Nagoya
158442  1841-11-01                 NaN                            NaN  Nagoya
158443  1841-12-01                 NaN                            NaN  Nagoya
158444  1842-01-01                 NaN                            NaN  Nagoya
158445  1842-02-01                 NaN                            NaN  Nagoya
158446  1842-03-01                 NaN                            NaN  Nagoya
158447  1842-04-01                 NaN                            NaN  Nagoya
158448  1842-05-01                 NaN                            NaN  Nagoya
158449  1842-06-01                 NaN                            NaN  Nagoya
158450  1842-07-01                 NaN                            NaN  Nagoya
158451  1842-08-01                 NaN                            NaN  Nagoya
158452  1842-09-01                 NaN                            NaN  Nagoya
158453  1842-10-01                 NaN                            NaN  Nagoya
158454  1842-11-01                 NaN                            NaN  Nagoya
158455  1842-12-01                 NaN                            NaN  Nagoya
158456  1843-01-01                 NaN                            NaN  Nagoya
158457  1843-02-01                 NaN                            NaN  Nagoya
158458  1843-03-01                 NaN                            NaN  Nagoya
158459  1843-04-01                 NaN                            NaN  Nagoya
158460  1843-05-01                 NaN                            NaN  Nagoya
158461  1843-06-01                 NaN                            NaN  Nagoya
158462  1843-07-01                 NaN                            NaN  Nagoya
158463  1843-08-01                 NaN                            NaN  Nagoya
158464  1843-09-01                 NaN                            NaN  Nagoya
...            ...                 ...                            ...     ...
229660  2011-04-01              11.175                          0.166   Tokyo
229661  2011-05-01              16.147                          0.149   Tokyo
229662  2011-06-01              21.085                          0.249   Tokyo
229663  2011-07-01              25.288                          0.300   Tokyo
229664  2011-08-01              25.202                          0.189   Tokyo
229665  2011-09-01              22.199                          0.152   Tokyo
229666  2011-10-01              15.488                          0.226   Tokyo
229667  2011-11-01              10.803                          0.245   Tokyo
229668  2011-12-01               3.250                          0.252   Tokyo
229669  2012-01-01               0.715                          0.319   Tokyo
229670  2012-02-01               1.842                          0.190   Tokyo
229671  2012-03-01               5.617                          0.157   Tokyo
229672  2012-04-01              11.355                          0.231   Tokyo
229673  2012-05-01              16.670                          0.262   Tokyo
229674  2012-06-01              19.359                          0.215   Tokyo
229675  2012-07-01              24.444                          0.388   Tokyo
229676  2012-08-01              26.681                          0.482   Tokyo
229677  2012-09-01              23.275                          0.348   Tokyo
229678  2012-10-01              15.722                          0.284   Tokyo
229679  2012-11-01               8.718                          0.316   Tokyo
229680  2012-12-01               2.961                          0.380   Tokyo
229681  2013-01-01               1.288                          0.287   Tokyo
229682  2013-02-01               2.046                          0.559   Tokyo
229683  2013-03-01               7.955                          1.120   Tokyo
229684  2013-04-01              11.310                          0.493   Tokyo
229685  2013-05-01              16.757                          0.396   Tokyo
229686  2013-06-01              20.927                          0.489   Tokyo
229687  2013-07-01              24.645                          0.404   Tokyo
229688  2013-08-01              26.364                          0.461   Tokyo
229689  2013-09-01                 NaN                            NaN   Tokyo

       Country Latitude Longitude
158435   Japan   34.56N   136.22E
158436   Japan   34.56N   136.22E
158437   Japan   34.56N   136.22E
158438   Japan   34.56N   136.22E
158439   Japan   34.56N   136.22E
158440   Japan   34.56N   136.22E
158441   Japan   34.56N   136.22E
158442   Japan   34.56N   136.22E
158443   Japan   34.56N   136.22E
158444   Japan   34.56N   136.22E
158445   Japan   34.56N   136.22E
158446   Japan   34.56N   136.22E
158447   Japan   34.56N   136.22E
158448   Japan   34.56N   136.22E
158449   Japan   34.56N   136.22E
158450   Japan   34.56N   136.22E
158451   Japan   34.56N   136.22E
158452   Japan   34.56N   136.22E
158453   Japan   34.56N   136.22E
158454   Japan   34.56N   136.22E
158455   Japan   34.56N   136.22E
158456   Japan   34.56N   136.22E
158457   Japan   34.56N   136.22E
158458   Japan   34.56N   136.22E
158459   Japan   34.56N   136.22E
158460   Japan   34.56N   136.22E
158461   Japan   34.56N   136.22E
158462   Japan   34.56N   136.22E
158463   Japan   34.56N   136.22E
158464   Japan   34.56N   136.22E
...        ...      ...       ...
229660   Japan   36.17N   139.23E
229661   Japan   36.17N   139.23E
229662   Japan   36.17N   139.23E
229663   Japan   36.17N   139.23E
229664   Japan   36.17N   139.23E
229665   Japan   36.17N   139.23E
229666   Japan   36.17N   139.23E
229667   Japan   36.17N   139.23E

[7355 rows x 7 columns]
Peru
                dt  AverageTemperature  AverageTemperatureUncertainty  City  \
127016  1881-03-01              20.013                          1.692  Lima
127017  1881-04-01              18.516                          1.649  Lima
127018  1881-05-01              16.673                          1.603  Lima
127019  1881-06-01              14.278                          1.714  Lima
127020  1881-07-01              13.748                          1.664  Lima
127021  1881-08-01              13.336                          1.556  Lima
127022  1881-09-01              13.968                          1.460  Lima
127023  1881-10-01              13.958                          1.451  Lima
127024  1881-11-01              15.030                          1.466  Lima
127025  1881-12-01              17.941                          1.558  Lima
127026  1882-01-01                 NaN                            NaN  Lima
127027  1882-02-01              20.831                          1.594  Lima
127028  1882-03-01              20.254                          1.666  Lima
127029  1882-04-01              17.580                          1.513  Lima
127030  1882-05-01              16.169                          1.608  Lima
127031  1882-06-01              14.073                          1.713  Lima
127032  1882-07-01              13.243                          1.736  Lima
127033  1882-08-01              13.636                          1.548  Lima
127034  1882-09-01              13.599                          1.436  Lima
127035  1882-10-01              13.541                          1.482  Lima
127036  1882-11-01                 NaN                            NaN  Lima
127037  1882-12-01                 NaN                            NaN  Lima
127038  1883-01-01              18.953                          1.552  Lima
127039  1883-02-01              19.610                          1.574  Lima
127040  1883-03-01              20.073                          1.670  Lima
127041  1883-04-01              17.837                          1.601  Lima
127042  1883-05-01              16.147                          1.707  Lima
127043  1883-06-01                 NaN                            NaN  Lima
127044  1883-07-01              13.357                          1.638  Lima
127045  1883-08-01              12.924                          1.551  Lima
...            ...                 ...                            ...   ...
128577  2011-04-01              18.362                          0.756  Lima
128578  2011-05-01              17.371                          0.439  Lima
128579  2011-06-01              16.665                          0.736  Lima
128580  2011-07-01              15.066                          0.971  Lima
128581  2011-08-01              14.387                          0.872  Lima
128582  2011-09-01              14.296                          0.746  Lima
128583  2011-10-01              14.965                          0.598  Lima
128584  2011-11-01              16.798                          0.426  Lima
128585  2011-12-01              18.293                          1.140  Lima
128586  2012-01-01              19.502                          0.802  Lima
128587  2012-02-01              20.387                          0.944  Lima
128588  2012-03-01              20.650                          0.582  Lima
128589  2012-04-01              19.863                          0.663  Lima
128590  2012-05-01              17.942                          0.343  Lima
128591  2012-06-01              17.054                          0.867  Lima
128592  2012-07-01              16.264                          1.335  Lima
128593  2012-08-01              14.806                          0.928  Lima
128594  2012-09-01              15.326                          0.525  Lima
128595  2012-10-01              15.367                          0.442  Lima
128596  2012-11-01              16.770                          0.409  Lima
128597  2012-12-01              18.240                          0.366  Lima
128598  2013-01-01              19.729                          0.990  Lima
128599  2013-02-01              20.519                          1.011  Lima
128600  2013-03-01              19.970                          0.619  Lima
128601  2013-04-01              17.756                          0.683  Lima
128602  2013-05-01              16.512                          0.751  Lima
128603  2013-06-01              14.491                          1.506  Lima
128604  2013-07-01              13.343                          1.452  Lima
128605  2013-08-01              13.643                          1.098  Lima
128606  2013-09-01                 NaN                            NaN  Lima

       Country Latitude Longitude
127016    Peru   12.05S    77.26W
127017    Peru   12.05S    77.26W
127018    Peru   12.05S    77.26W
127019    Peru   12.05S    77.26W
127020    Peru   12.05S    77.26W
127021    Peru   12.05S    77.26W
127022    Peru   12.05S    77.26W
127023    Peru   12.05S    77.26W
127024    Peru   12.05S    77.26W
127025    Peru   12.05S    77.26W
127026    Peru   12.05S    77.26W
127027    Peru   12.05S    77.26W
127028    Peru   12.05S    77.26W
127029    Peru   12.05S    77.26W
127030    Peru   12.05S    77.26W
127031    Peru   12.05S    77.26W
127032    Peru   12.05S    77.26W
127033    Peru   12.05S    77.26W
127034    Peru   12.05S    77.26W
127035    Peru   12.05S    77.26W
127036    Peru   12.05S    77.26W
127037    Peru   12.05S    77.26W
127038    Peru   12.05S    77.26W
127039    Peru   12.05S    77.26W
127040    Peru   12.05S    77.26W
127041    Peru   12.05S    77.26W
127042    Peru   12.05S    77.26W
127043    Peru   12.05S    77.26W
127044    Peru   12.05S    77.26W
127045    Peru   12.05S    77.26W
...        ...      ...       ...
128577    Peru   12.05S    77.26W
128578    Peru   12.05S    77.26W
128579    Peru   12.05S    77.26W
128580    Peru   12.05S    77.26W
128581    Peru   12.05S    77.26W
128582    Peru   12.05S    77.26W
128583    Peru   12.05S    77.26W
128584    Peru   12.05S    77.26W
128585    Peru   12.05S    77.26W
128586    Peru   12.05S    77.26W
128587    Peru   12.05S    77.26W
128588    Peru   12.05S    77.26W
128589    Peru   12.05S    77.26W
128590    Peru   12.05S    77.26W
128591    Peru   12.05S    77.26W
128592    Peru   12.05S    77.26W
128593    Peru   12.05S    77.26W
128594    Peru   12.05S    77.26W
128595    Peru   12.05S    77.26W
128596    Peru   12.05S    77.26W
128597    Peru   12.05S    77.26W
128598    Peru   12.05S    77.26W
128599    Peru   12.05S    77.26W
128600    Peru   12.05S    77.26W
128601    Peru   12.05S    77.26W
128602    Peru   12.05S    77.26W
128603    Peru   12.05S    77.26W
128604    Peru   12.05S    77.26W
128605    Peru   12.05S    77.26W
128606    Peru   12.05S    77.26W

[1591 rows x 7 columns]
Philippines
                dt  AverageTemperature  AverageTemperatureUncertainty    City  \
141568  1845-01-01              24.995                          1.871  Manila
141569  1845-02-01              24.630                          2.228  Manila
141570  1845-03-01              26.512                          1.369  Manila
141571  1845-04-01                 NaN                            NaN  Manila
141572  1845-05-01              27.564                          1.498  Manila
141573  1845-06-01              26.819                          1.380  Manila
141574  1845-07-01              26.414                          1.306  Manila
141575  1845-08-01              25.856                          1.157  Manila
141576  1845-09-01              25.289                          1.172  Manila
141577  1845-10-01              24.628                          1.225  Manila
141578  1845-11-01              24.581                          1.429  Manila
141579  1845-12-01              23.316                          1.935  Manila
141580  1846-01-01              25.646                          1.782  Manila
141581  1846-02-01              25.760                          1.639  Manila
141582  1846-03-01              27.860                          1.556  Manila
141583  1846-04-01              27.318                          1.420  Manila
141584  1846-05-01              27.845                          1.687  Manila
141585  1846-06-01              27.626                          1.439  Manila
141586  1846-07-01              26.986                          1.507  Manila
141587  1846-08-01              26.481                          1.266  Manila
141588  1846-09-01              25.883                          1.405  Manila
141589  1846-10-01              25.257                          1.256  Manila
141590  1846-11-01              24.963                          1.593  Manila
141591  1846-12-01              25.330                          1.454  Manila
141592  1847-01-01              24.749                          3.850  Manila
141593  1847-02-01              25.550                          1.524  Manila
141594  1847-03-01              25.977                          2.112  Manila
141595  1847-04-01              27.632                          1.396  Manila
141596  1847-05-01              27.330                          1.381  Manila
141597  1847-06-01              26.613                          1.424  Manila
...            ...                 ...                            ...     ...
143563  2011-04-01              27.843                          0.219  Manila
143564  2011-05-01              28.827                          0.114  Manila
143565  2011-06-01              27.416                          0.211  Manila
143566  2011-07-01              26.919                          0.213  Manila
143567  2011-08-01              26.794                          0.168  Manila
143568  2011-09-01              26.518                          0.177  Manila
143569  2011-10-01              26.813                          0.225  Manila
143570  2011-11-01              26.626                          0.252  Manila
143571  2011-12-01              25.882                          0.276  Manila
143572  2012-01-01              26.020                          0.366  Manila
143573  2012-02-01              26.764                          0.406  Manila
143574  2012-03-01              27.883                          0.347  Manila
143575  2012-04-01              29.293                          0.226  Manila
143576  2012-05-01              29.139                          0.449  Manila
143577  2012-06-01              27.799                          0.417  Manila
143578  2012-07-01              26.959                          0.360  Manila
143579  2012-08-01              26.531                          0.583  Manila
143580  2012-09-01              27.246                          0.357  Manila
143581  2012-10-01              26.632                          0.297  Manila
143582  2012-11-01              27.191                          0.504  Manila
143583  2012-12-01              26.580                          0.442  Manila
143584  2013-01-01              25.497                          0.246  Manila
143585  2013-02-01              27.042                          0.364  Manila
143586  2013-03-01              28.264                          0.807  Manila
143587  2013-04-01              30.005                          0.357  Manila
143588  2013-05-01              29.552                          0.248  Manila
143589  2013-06-01              28.572                          0.475  Manila
143590  2013-07-01              27.266                          0.604  Manila
143591  2013-08-01              26.754                          0.381  Manila
143592  2013-09-01                 NaN                            NaN  Manila

            Country Latitude Longitude
141568  Philippines   15.27N   120.83E
141569  Philippines   15.27N   120.83E
141570  Philippines   15.27N   120.83E
141571  Philippines   15.27N   120.83E
141572  Philippines   15.27N   120.83E
141573  Philippines   15.27N   120.83E
141574  Philippines   15.27N   120.83E
141575  Philippines   15.27N   120.83E
141576  Philippines   15.27N   120.83E
141577  Philippines   15.27N   120.83E
141578  Philippines   15.27N   120.83E
141579  Philippines   15.27N   120.83E
141580  Philippines   15.27N   120.83E
141581  Philippines   15.27N   120.83E
141582  Philippines   15.27N   120.83E
141583  Philippines   15.27N   120.83E
141584  Philippines   15.27N   120.83E
141585  Philippines   15.27N   120.83E
141586  Philippines   15.27N   120.83E
141587  Philippines   15.27N   120.83E
141588  Philippines   15.27N   120.83E
141589  Philippines   15.27N   120.83E
141590  Philippines   15.27N   120.83E
141591  Philippines   15.27N   120.83E
141592  Philippines   15.27N   120.83E
141593  Philippines   15.27N   120.83E
141594  Philippines   15.27N   120.83E
141595  Philippines   15.27N   120.83E
141596  Philippines   15.27N   120.83E
141597  Philippines   15.27N   120.83E
...             ...      ...       ...
143563  Philippines   15.27N   120.83E
143564  Philippines   15.27N   120.83E
143565  Philippines   15.27N   120.83E
143566  Philippines   15.27N   120.83E
143567  Philippines   15.27N   120.83E
143568  Philippines   15.27N   120.83E
143569  Philippines   15.27N   120.83E
143570  Philippines   15.27N   120.83E
143571  Philippines   15.27N   120.83E
143572  Philippines   15.27N   120.83E
143573  Philippines   15.27N   120.83E
143574  Philippines   15.27N   120.83E
143575  Philippines   15.27N   120.83E
143576  Philippines   15.27N   120.83E
143577  Philippines   15.27N   120.83E
143578  Philippines   15.27N   120.83E
143579  Philippines   15.27N   120.83E
143580  Philippines   15.27N   120.83E
143581  Philippines   15.27N   120.83E
143582  Philippines   15.27N   120.83E
143583  Philippines   15.27N   120.83E
143584  Philippines   15.27N   120.83E
143585  Philippines   15.27N   120.83E
143586  Philippines   15.27N   120.83E
143587  Philippines   15.27N   120.83E
143588  Philippines   15.27N   120.83E
143589  Philippines   15.27N   120.83E
143590  Philippines   15.27N   120.83E
143591  Philippines   15.27N   120.83E
143592  Philippines   15.27N   120.83E

[2025 rows x 7 columns]
Russia
                dt  AverageTemperature  AverageTemperatureUncertainty  \
155196  1743-11-01              -2.570                          2.037
155197  1743-12-01                 NaN                            NaN
155198  1744-01-01                 NaN                            NaN
155199  1744-02-01                 NaN                            NaN
155200  1744-03-01                 NaN                            NaN
155201  1744-04-01               6.555                          2.544
155202  1744-05-01              10.063                          1.875
155203  1744-06-01              15.393                          1.732
155204  1744-07-01              17.584                          1.543
155205  1744-08-01                 NaN                            NaN
155206  1744-09-01              10.765                          1.590
155207  1744-10-01               1.978                          1.793
155208  1744-11-01              -1.648                          1.842
155209  1744-12-01              -7.535                          2.261
155210  1745-01-01             -11.656                          2.341
155211  1745-02-01             -10.205                          2.214
155212  1745-03-01              -5.839                          1.887
155213  1745-04-01               3.167                          1.738
155214  1745-05-01                 NaN                            NaN
155215  1745-06-01                 NaN                            NaN
155216  1745-07-01                 NaN                            NaN
155217  1745-08-01                 NaN                            NaN
155218  1745-09-01                 NaN                            NaN
155219  1745-10-01                 NaN                            NaN
155220  1745-11-01                 NaN                            NaN
155221  1745-12-01                 NaN                            NaN
155222  1746-01-01                 NaN                            NaN
155223  1746-02-01                 NaN                            NaN
155224  1746-03-01                 NaN                            NaN
155225  1746-04-01                 NaN                            NaN
...            ...                 ...                            ...
196650  2011-04-01               4.146                          0.339
196651  2011-05-01               9.442                          0.219
196652  2011-06-01              15.823                          0.221
196653  2011-07-01              20.389                          0.211
196654  2011-08-01              16.426                          0.282
196655  2011-09-01              12.704                          0.183
196656  2011-10-01               7.691                          0.166
196657  2011-11-01               4.454                          0.375
196658  2011-12-01               2.647                          0.488
196659  2012-01-01              -5.211                          0.370
196660  2012-02-01             -10.957                          0.275
196661  2012-03-01              -1.624                          0.307
196662  2012-04-01               2.877                          0.369
196663  2012-05-01              10.349                          0.200
196664  2012-06-01              12.955                          0.317
196665  2012-07-01              17.733                          0.261
196666  2012-08-01              15.219                          0.340
196667  2012-09-01              12.251                          0.312
196668  2012-10-01               6.208                          0.241
196669  2012-11-01               3.448                          0.336
196670  2012-12-01              -7.316                          0.775
196671  2013-01-01              -6.218                          0.298
196672  2013-02-01              -3.228                          0.508
196673  2013-03-01              -8.178                          0.194
196674  2013-04-01               2.167                          0.473
196675  2013-05-01              12.355                          0.195
196676  2013-06-01              17.185                          0.413
196677  2013-07-01              17.234                          0.273
196678  2013-08-01              17.153                          0.279
196679  2013-09-01                 NaN                            NaN

                    City Country Latitude Longitude
155196            Moscow  Russia   55.45N    36.85E
155197            Moscow  Russia   55.45N    36.85E
155198            Moscow  Russia   55.45N    36.85E
155199            Moscow  Russia   55.45N    36.85E
155200            Moscow  Russia   55.45N    36.85E
155201            Moscow  Russia   55.45N    36.85E
155202            Moscow  Russia   55.45N    36.85E
155203            Moscow  Russia   55.45N    36.85E
155204            Moscow  Russia   55.45N    36.85E
155205            Moscow  Russia   55.45N    36.85E
155206            Moscow  Russia   55.45N    36.85E
155207            Moscow  Russia   55.45N    36.85E
155208            Moscow  Russia   55.45N    36.85E
155209            Moscow  Russia   55.45N    36.85E
155210            Moscow  Russia   55.45N    36.85E
155211            Moscow  Russia   55.45N    36.85E
155212            Moscow  Russia   55.45N    36.85E
155213            Moscow  Russia   55.45N    36.85E
155214            Moscow  Russia   55.45N    36.85E
155215            Moscow  Russia   55.45N    36.85E
155216            Moscow  Russia   55.45N    36.85E
155217            Moscow  Russia   55.45N    36.85E
155218            Moscow  Russia   55.45N    36.85E
155219            Moscow  Russia   55.45N    36.85E
155220            Moscow  Russia   55.45N    36.85E
155221            Moscow  Russia   55.45N    36.85E
155222            Moscow  Russia   55.45N    36.85E

                dt  AverageTemperature  AverageTemperatureUncertainty  \
149992  1850-01-01              25.424                          1.395
149993  1850-02-01              27.180                          1.441
149994  1850-03-01              28.037                          2.109
149995  1850-04-01              27.781                          1.589
149996  1850-05-01              26.716                          1.144
149997  1850-06-01              26.336                          1.132
149998  1850-07-01              25.828                          1.099
149999  1850-08-01              25.841                          1.056
150000  1850-09-01              25.740                          1.127
150001  1850-10-01              25.881                          1.300
150002  1850-11-01              25.980                          1.591
150003  1850-12-01                 NaN                            NaN
150004  1851-01-01                 NaN                            NaN
150005  1851-02-01                 NaN                            NaN
150006  1851-03-01                 NaN                            NaN
150007  1851-04-01                 NaN                            NaN
150008  1851-05-01                 NaN                            NaN
150009  1851-06-01                 NaN                            NaN
150010  1851-07-01                 NaN                            NaN
150011  1851-08-01                 NaN                            NaN
150012  1851-09-01                 NaN                            NaN
150013  1851-10-01                 NaN                            NaN
150014  1851-11-01                 NaN                            NaN
150015  1851-12-01                 NaN                            NaN
150016  1852-01-01                 NaN                            NaN
150017  1852-02-01                 NaN                            NaN
150018  1852-03-01                 NaN                            NaN
150019  1852-04-01                 NaN                            NaN
150020  1852-05-01                 NaN                            NaN
150021  1852-06-01                 NaN                            NaN
...            ...                 ...                            ...
151927  2011-04-01              30.238                          0.815
151928  2011-05-01              29.660                          0.907
151929  2011-06-01              28.329                          0.723
151930  2011-07-01              27.544                          0.637
151931  2011-08-01              27.425                          0.568
151932  2011-09-01              28.323                          0.510
151933  2011-10-01              27.455                          0.804
151934  2011-11-01              28.278                          1.020
151935  2011-12-01              27.408                          0.818
151936  2012-01-01              27.564                          0.631
151937  2012-02-01              27.857                          0.701
151938  2012-03-01              29.090                          0.619
151939  2012-04-01              29.841                          0.653
151940  2012-05-01              28.995                          0.527
151941  2012-06-01              27.987                          0.542
151942  2012-07-01              26.603                          1.688
151943  2012-08-01              27.511                          0.957
151944  2012-09-01              28.288                          0.791
151945  2012-10-01              27.804                          1.059
151946  2012-11-01              28.311                          0.721
151947  2012-12-01              28.423                          0.810
151948  2013-01-01              27.451                          1.284
151949  2013-02-01              27.535                          1.805
151950  2013-03-01              28.822                          1.174
151951  2013-04-01              29.673                          1.460
151952  2013-05-01              29.203                          0.773
151953  2013-06-01              27.391                          1.011
151954  2013-07-01              26.517                          0.780
151955  2013-08-01              26.939                          1.475
151956  2013-09-01                 NaN                            NaN

             City  Country Latitude Longitude
149992  Mogadishu  Somalia    2.41N    45.80E
149993  Mogadishu  Somalia    2.41N    45.80E
149994  Mogadishu  Somalia    2.41N    45.80E
149995  Mogadishu  Somalia    2.41N    45.80E
149996  Mogadishu  Somalia    2.41N    45.80E
149997  Mogadishu  Somalia    2.41N    45.80E
149998  Mogadishu  Somalia    2.41N    45.80E
149999  Mogadishu  Somalia    2.41N    45.80E
150000  Mogadishu  Somalia    2.41N    45.80E
150001  Mogadishu  Somalia    2.41N    45.80E
150002  Mogadishu  Somalia    2.41N    45.80E
150003  Mogadishu  Somalia    2.41N    45.80E
150004  Mogadishu  Somalia    2.41N    45.80E
150005  Mogadishu  Somalia    2.41N    45.80E
150006  Mogadishu  Somalia    2.41N    45.80E
150007  Mogadishu  Somalia    2.41N    45.80E
150008  Mogadishu  Somalia    2.41N    45.80E
150009  Mogadishu  Somalia    2.41N    45.80E
150010  Mogadishu  Somalia    2.41N    45.80E
150011  Mogadishu  Somalia    2.41N    45.80E
150012  Mogadishu  Somalia    2.41N    45.80E
150013  Mogadishu  Somalia    2.41N    45.80E
150014  Mogadishu  Somalia    2.41N    45.80E
150015  Mogadishu  Somalia    2.41N    45.80E
150016  Mogadishu  Somalia    2.41N    45.80E
150017  Mogadishu  Somalia    2.41N    45.80E
150018  Mogadishu  Somalia    2.41N    45.80E
150019  Mogadishu  Somalia    2.41N    45.80E
150020  Mogadishu  Somalia    2.41N    45.80E
150021  Mogadishu  Somalia    2.41N    45.80E
...           ...      ...      ...       ...
151927  Mogadishu  Somalia    2.41N    45.80E
151928  Mogadishu  Somalia    2.41N    45.80E
151929  Mogadishu  Somalia    2.41N    45.80E
151930  Mogadishu  Somalia    2.41N    45.80E
151931  Mogadishu  Somalia    2.41N    45.80E
151932  Mogadishu  Somalia    2.41N    45.80E
151933  Mogadishu  Somalia    2.41N    45.80E
151934  Mogadishu  Somalia    2.41N    45.80E
151935  Mogadishu  Somalia    2.41N    45.80E
151936  Mogadishu  Somalia    2.41N    45.80E
151937  Mogadishu  Somalia    2.41N    45.80E
151938  Mogadishu  Somalia    2.41N    45.80E
151939  Mogadishu  Somalia    2.41N    45.80E
151940  Mogadishu  Somalia    2.41N    45.80E
151941  Mogadishu  Somalia    2.41N    45.80E
151942  Mogadishu  Somalia    2.41N    45.80E
151943  Mogadishu  Somalia    2.41N    45.80E
151944  Mogadishu  Somalia    2.41N    45.80E
151945  Mogadishu  Somalia    2.41N    45.80E
151946  Mogadishu  Somalia    2.41N    45.80E
151947  Mogadishu  Somalia    2.41N    45.80E
151948  Mogadishu  Somalia    2.41N    45.80E
151949  Mogadishu  Somalia    2.41N    45.80E
151950  Mogadishu  Somalia    2.41N    45.80E
151951  Mogadishu  Somalia    2.41N    45.80E
151952  Mogadishu  Somalia    2.41N    45.80E
151953  Mogadishu  Somalia    2.41N    45.80E
151954  Mogadishu  Somalia    2.41N    45.80E
151955  Mogadishu  Somalia    2.41N    45.80E
151956  Mogadishu  Somalia    2.41N    45.80E

[1965 rows x 7 columns]
South Africa
               dt  AverageTemperature  AverageTemperatureUncertainty  \
42148  1857-01-01              18.455                          2.178
42149  1857-02-01              19.761                          1.283
42150  1857-03-01              17.954                          1.277
42151  1857-04-01              14.790                          1.515
42152  1857-05-01              13.720                          1.506
42153  1857-06-01              11.175                          1.492
42154  1857-07-01              11.242                          1.199
42155  1857-08-01              12.584                          2.016
42156  1857-09-01              13.557                          1.714
42157  1857-10-01              14.641                          1.200
42158  1857-11-01              17.267                          1.283
42159  1857-12-01              17.906                          2.354
42160  1858-01-01              18.817                          3.568
42161  1858-02-01              18.884                          1.459
42162  1858-03-01              18.043                          1.746
42163  1858-04-01              17.260                          1.341
42164  1858-05-01              13.777                          1.700
42165  1858-06-01              12.739                          1.429
42166  1858-07-01              10.091                          2.810
42167  1858-08-01              11.976                          1.145
42168  1858-09-01              13.411                          1.215
42169  1858-10-01              15.080                          1.155
42170  1858-11-01              17.583                          1.301
42171  1858-12-01              18.210                          1.540
42172  1859-01-01              19.104                          1.639
42173  1859-02-01              18.563                          2.811
42174  1859-03-01              18.769                          1.344
42175  1859-04-01              16.196                          2.363
42176  1859-05-01              14.568                          0.956
42177  1859-06-01              12.434                          1.120
...           ...                 ...                            ...
70230  2011-04-01              21.109                          0.485
70231  2011-05-01              20.261                          0.340
70232  2011-06-01              17.759                          0.972
70233  2011-07-01              16.671                          0.410
70234  2011-08-01              17.914                          0.567
70235  2011-09-01              20.003                          0.160
70236  2011-10-01              20.232                          0.394
70237  2011-11-01              20.584                          0.585
70238  2011-12-01              22.205                          0.381
70239  2012-01-01              24.201                          0.503
70240  2012-02-01              24.553                          0.347
70241  2012-03-01              23.560                          0.241
70242  2012-04-01              20.602                          0.242
70243  2012-05-01              20.965                          0.230
70244  2012-06-01              19.139                          0.694
70245  2012-07-01              17.934                          1.207
70246  2012-08-01              20.089                          0.594
70247  2012-09-01              19.220                          0.802
70248  2012-10-01              20.633                          0.861
70249  2012-11-01              21.140                          0.552
70250  2012-12-01              22.879                          1.128
70251  2013-01-01              23.632                          0.876
70252  2013-02-01              23.890                          0.546
70253  2013-03-01              23.516                          1.271
70254  2013-04-01              21.428                          0.572
70255  2013-05-01              20.101                          0.384
70256  2013-06-01              19.175                          1.139
70257  2013-07-01              18.990                          0.432
70258  2013-08-01              19.711                          0.841
70259  2013-09-01                 NaN                            NaN

            City       Country Latitude Longitude
42148  Cape Town  South Africa   32.95S    18.19E
42149  Cape Town  South Africa   32.95S    18.19E
42150  Cape Town  South Africa   32.95S    18.19E
42151  Cape Town  South Africa   32.95S    18.19E
42152  Cape Town  South Africa   32.95S    18.19E
42153  Cape Town  South Africa   32.95S    18.19E
42154  Cape Town  South Africa   32.95S    18.19E
42155  Cape Town  South Africa   32.95S    18.19E
42156  Cape Town  South Africa   32.95S    18.19E
42157  Cape Town  South Africa   32.95S    18.19E
42158  Cape Town  South Africa   32.95S    18.19E
42159  Cape Town  South Africa   32.95S    18.19E
42160  Cape Town  South Africa   32.95S    18.19E
42161  Cape Town  South Africa   32.95S    18.19E
42162  Cape Town  South Africa   32.95S    18.19E
42163  Cape Town  South Africa   32.95S    18.19E
42164  Cape Town  South Africa   32.95S    18.19E
42165  Cape Town  South Africa   32.95S    18.19E
42166  Cape Town  South Africa   32.95S    18.19E
42167  Cape Town  South Africa   32.95S    18.19E
42168  Cape Town  South Africa   32.95S    18.19E
42169  Cape Town  South Africa   32.95S    18.19E
42170  Cape Town  South Africa   32.95S    18.19E
42171  Cape Town  South Africa   32.95S    18.19E
42172  Cape Town  South Africa   32.95S    18.19E
42173  Cape Town  South Africa   32.95S    18.19E
42174  Cape Town  South Africa   32.95S    18.19E
42175  Cape Town  South Africa   32.95S    18.19E
42176  Cape Town  South Africa   32.95S    18.19E
42177  Cape Town  South Africa   32.95S    18.19E
...          ...           ...      ...       ...
70230     Durban  South Africa   29.74S    31.38E
70231     Durban  South Africa   29.74S    31.38E
70232     Durban  South Africa   29.74S    31.38E
70233     Durban  South Africa   29.74S    31.38E
70234     Durban  South Africa   29.74S    31.38E
70235     Durban  South Africa   29.74S    31.38E
70236     Durban  South Africa   29.74S    31.38E
70237     Durban  South Africa   29.74S    31.38E
70238     Durban  South Africa   29.74S    31.38E
70239     Durban  South Africa   29.74S    31.38E
70240     Durban  South Africa   29.74S    31.38E
70241     Durban  South Africa   29.74S    31.38E
70242     Durban  South Africa   29.74S    31.38E
70243     Durban  South Africa   29.74S    31.38E
70244     Durban  South Africa   29.74S    31.38E
70245     Durban  South Africa   29.74S    31.38E
70246     Durban  South Africa   29.74S    31.38E
70247     Durban  South Africa   29.74S    31.38E
70248     Durban  South Africa   29.74S    31.38E
70249     Durban  South Africa   29.74S    31.38E
70250     Durban  South Africa   29.74S    31.38E
70251     Durban  South Africa   29.74S    31.38E
70252     Durban  South Africa   29.74S    31.38E
70253     Durban  South Africa   29.74S    31.38E
70254     Durban  South Africa   29.74S    31.38E
70255     Durban  South Africa   29.74S    31.38E
70256     Durban  South Africa   29.74S    31.38E
70257     Durban  South Africa   29.74S    31.38E
70258     Durban  South Africa   29.74S    31.38E
70259     Durban  South Africa   29.74S    31.38E

[3762 rows x 7 columns]
South Korea
                dt  AverageTemperature  AverageTemperatureUncertainty   City  \
203039  1839-01-01              -4.570                          2.394  Seoul
203040  1839-02-01              -2.520                          2.602  Seoul
203041  1839-03-01               0.678                          2.041  Seoul
203042  1839-04-01               8.828                          2.068  Seoul
203043  1839-05-01              14.278                          1.546  Seoul
203044  1839-06-01              19.294                          1.508  Seoul
203045  1839-07-01              23.062                          2.967  Seoul
203046  1839-08-01              23.785                          2.104  Seoul
203047  1839-09-01              19.154                          1.720  Seoul
203048  1839-10-01              11.459                          2.697  Seoul
203049  1839-11-01               3.906                          2.483  Seoul
203050  1839-12-01              -3.706                          2.575  Seoul
203051  1840-01-01              -3.682                          2.665  Seoul
203052  1840-02-01              -2.838                          2.481  Seoul
203053  1840-03-01               1.604                          2.094  Seoul
203054  1840-04-01               9.527                          2.330  Seoul
203055  1840-05-01              15.378                          1.953  Seoul
203056  1840-06-01              20.008                          1.809  Seoul
203057  1840-07-01              24.417                          1.987  Seoul
203058  1840-08-01              23.681                          2.103  Seoul
203059  1840-09-01              19.004                          1.613  Seoul
203060  1840-10-01              12.179                          2.191  Seoul
203061  1840-11-01               5.444                          3.585  Seoul
203062  1840-12-01              -2.211                          2.642  Seoul
203063  1841-01-01              -6.138                          2.698  Seoul
203064  1841-02-01              -3.502                          2.003  Seoul
203065  1841-03-01               1.019                          1.593  Seoul
203066  1841-04-01               8.563                          2.054  Seoul
203067  1841-05-01              14.490                          1.303  Seoul
203068  1841-06-01              18.479                          3.202  Seoul
...            ...                 ...                            ...    ...
205106  2011-04-01               9.605                          0.184  Seoul
205107  2011-05-01              16.563                          0.375  Seoul
205108  2011-06-01              20.182                          0.591  Seoul
205109  2011-07-01              23.659                          0.351  Seoul
205110  2011-08-01              24.620                          0.356  Seoul
205111  2011-09-01              20.599                          0.230  Seoul
205112  2011-10-01              13.330                          0.145  Seoul
205113  2011-11-01              10.009                          0.274  Seoul
205114  2011-12-01              -1.228                          0.213  Seoul
205115  2012-01-01              -3.778                          0.286  Seoul
205116  2012-02-01              -2.707                          0.229  Seoul
205117  2012-03-01               4.172                          0.247  Seoul
205118  2012-04-01              11.081                          0.458  Seoul
205119  2012-05-01              18.019                          0.382  Seoul
205120  2012-06-01              21.961                          0.412  Seoul
205121  2012-07-01              24.210                          0.469  Seoul
205122  2012-08-01              25.818                          0.255  Seoul
205123  2012-09-01              20.333                          0.341  Seoul
205124  2012-10-01              14.493                          0.349  Seoul
205125  2012-11-01               5.403                          0.268  Seoul
205126  2012-12-01              -4.280                          0.511  Seoul
205127  2013-01-01              -4.203                          0.490  Seoul
205128  2013-02-01              -1.914                          0.384  Seoul
205129  2013-03-01               4.106                          0.568  Seoul
205130  2013-04-01               8.619                          0.296  Seoul
205131  2013-05-01              16.818                          0.537  Seoul
205132  2013-06-01              21.878                          0.476  Seoul
205133  2013-07-01              24.852                          0.887  Seoul
205134  2013-08-01              26.791                          0.345  Seoul
205135  2013-09-01                 NaN                            NaN  Seoul

            Country Latitude Longitude
203039  South Korea   37.78N   126.10E
203040  South Korea   37.78N   126.10E
203041  South Korea   37.78N   126.10E
203042  South Korea   37.78N   126.10E
203043  South Korea   37.78N   126.10E
203044  South Korea   37.78N   126.10E
203045  South Korea   37.78N   126.10E
203046  South Korea   37.78N   126.10E
203047  South Korea   37.78N   126.10E
203048  South Korea   37.78N   126.10E
203049  South Korea   37.78N   126.10E
203050  South Korea   37.78N   126.10E
203051  South Korea   37.78N   126.10E

               dt  AverageTemperature  AverageTemperatureUncertainty  \
61188  1850-01-01              26.794                          1.686
61189  1850-02-01              27.291                          1.633
61190  1850-03-01              27.032                          2.329
61191  1850-04-01              25.710                          1.603
61192  1850-05-01              24.194                          0.912
61193  1850-06-01              24.025                          0.891
61194  1850-07-01              23.402                          0.801
61195  1850-08-01              23.285                          0.680
61196  1850-09-01              23.116                          0.822
61197  1850-10-01              23.797                          1.251
61198  1850-11-01              24.779                          1.795
61199  1850-12-01                 NaN                            NaN
61200  1851-01-01                 NaN                            NaN
61201  1851-02-01                 NaN                            NaN
61202  1851-03-01                 NaN                            NaN
61203  1851-04-01                 NaN                            NaN
61204  1851-05-01                 NaN                            NaN
61205  1851-06-01                 NaN                            NaN
61206  1851-07-01                 NaN                            NaN
61207  1851-08-01                 NaN                            NaN
61208  1851-09-01                 NaN                            NaN
61209  1851-10-01                 NaN                            NaN
61210  1851-11-01                 NaN                            NaN
61211  1851-12-01                 NaN                            NaN
61212  1852-01-01                 NaN                            NaN
61213  1852-02-01                 NaN                            NaN
61214  1852-03-01                 NaN                            NaN
61215  1852-04-01                 NaN                            NaN
61216  1852-05-01                 NaN                            NaN
61217  1852-06-01                 NaN                            NaN
...           ...                 ...                            ...
63123  2011-04-01              27.168                          0.230
63124  2011-05-01              26.486                          0.287
63125  2011-06-01              25.490                          0.287
63126  2011-07-01              24.618                          0.496
63127  2011-08-01              24.473                          0.220
63128  2011-09-01              25.042                          0.359
63129  2011-10-01              25.524                          0.182
63130  2011-11-01              26.783                          0.302
63131  2011-12-01              27.637                          0.486
63132  2012-01-01              28.170                          0.361
63133  2012-02-01              28.493                          0.314
63134  2012-03-01              28.164                          0.294
63135  2012-04-01              27.137                          0.335
63136  2012-05-01              26.040                          0.279
63137  2012-06-01              25.148                          0.276
63138  2012-07-01              24.348                          0.541
63139  2012-08-01              24.581                          0.316
63140  2012-09-01              24.948                          0.380
63141  2012-10-01              25.768                          0.578
63142  2012-11-01              27.138                          0.401
63143  2012-12-01              28.164                          0.728
63144  2013-01-01              28.761                          1.108
63145  2013-02-01              29.052                          0.829
63146  2013-03-01              28.238                          0.911
63147  2013-04-01              27.858                          2.151
63148  2013-05-01              26.219                          0.500
63149  2013-06-01              25.106                          0.472
63150  2013-07-01              24.512                          0.446
63151  2013-08-01              24.359                          0.690
63152  2013-09-01                 NaN                            NaN

                City   Country Latitude Longitude
61188  Dar Es Salaam  Tanzania    7.23S    39.73E
61189  Dar Es Salaam  Tanzania    7.23S    39.73E
61190  Dar Es Salaam  Tanzania    7.23S    39.73E
61191  Dar Es Salaam  Tanzania    7.23S    39.73E
61192  Dar Es Salaam  Tanzania    7.23S    39.73E
61193  Dar Es Salaam  Tanzania    7.23S    39.73E
61194  Dar Es Salaam  Tanzania    7.23S    39.73E
61195  Dar Es Salaam  Tanzania    7.23S    39.73E
61196  Dar Es Salaam  Tanzania    7.23S    39.73E
61197  Dar Es Salaam  Tanzania    7.23S    39.73E
61198  Dar Es Salaam  Tanzania    7.23S    39.73E
61199  Dar Es Salaam  Tanzania    7.23S    39.73E
61200  Dar Es Salaam  Tanzania    7.23S    39.73E
61201  Dar Es Salaam  Tanzania    7.23S    39.73E
61202  Dar Es Salaam  Tanzania    7.23S    39.73E
61203  Dar Es Salaam  Tanzania    7.23S    39.73E
61204  Dar Es Salaam  Tanzania    7.23S    39.73E
61205  Dar Es Salaam  Tanzania    7.23S    39.73E
61206  Dar Es Salaam  Tanzania    7.23S    39.73E
61207  Dar Es Salaam  Tanzania    7.23S    39.73E
61208  Dar Es Salaam  Tanzania    7.23S    39.73E
61209  Dar Es Salaam  Tanzania    7.23S    39.73E
61210  Dar Es Salaam  Tanzania    7.23S    39.73E
61211  Dar Es Salaam  Tanzania    7.23S    39.73E
61212  Dar Es Salaam  Tanzania    7.23S    39.73E
61213  Dar Es Salaam  Tanzania    7.23S    39.73E
61214  Dar Es Salaam  Tanzania    7.23S    39.73E
61215  Dar Es Salaam  Tanzania    7.23S    39.73E
61216  Dar Es Salaam  Tanzania    7.23S    39.73E
61217  Dar Es Salaam  Tanzania    7.23S    39.73E
...              ...       ...      ...       ...
63123  Dar Es Salaam  Tanzania    7.23S    39.73E
63124  Dar Es Salaam  Tanzania    7.23S    39.73E
63125  Dar Es Salaam  Tanzania    7.23S    39.73E
63126  Dar Es Salaam  Tanzania    7.23S    39.73E
63127  Dar Es Salaam  Tanzania    7.23S    39.73E
63128  Dar Es Salaam  Tanzania    7.23S    39.73E
63129  Dar Es Salaam  Tanzania    7.23S    39.73E
63130  Dar Es Salaam  Tanzania    7.23S    39.73E
63131  Dar Es Salaam  Tanzania    7.23S    39.73E
63132  Dar Es Salaam  Tanzania    7.23S    39.73E
63133  Dar Es Salaam  Tanzania    7.23S    39.73E
63134  Dar Es Salaam  Tanzania    7.23S    39.73E
63135  Dar Es Salaam  Tanzania    7.23S    39.73E
63136  Dar Es Salaam  Tanzania    7.23S    39.73E
63137  Dar Es Salaam  Tanzania    7.23S    39.73E
63138  Dar Es Salaam  Tanzania    7.23S    39.73E
63139  Dar Es Salaam  Tanzania    7.23S    39.73E
63140  Dar Es Salaam  Tanzania    7.23S    39.73E
63141  Dar Es Salaam  Tanzania    7.23S    39.73E
63142  Dar Es Salaam  Tanzania    7.23S    39.73E
63143  Dar Es Salaam  Tanzania    7.23S    39.73E
63144  Dar Es Salaam  Tanzania    7.23S    39.73E
63145  Dar Es Salaam  Tanzania    7.23S    39.73E
63146  Dar Es Salaam  Tanzania    7.23S    39.73E
63147  Dar Es Salaam  Tanzania    7.23S    39.73E
63148  Dar Es Salaam  Tanzania    7.23S    39.73E
63149  Dar Es Salaam  Tanzania    7.23S    39.73E
63150  Dar Es Salaam  Tanzania    7.23S    39.73E
63151  Dar Es Salaam  Tanzania    7.23S    39.73E
63152  Dar Es Salaam  Tanzania    7.23S    39.73E

[1965 rows x 7 columns]
Thailand
               dt  AverageTemperature  AverageTemperatureUncertainty     City  \
19948  1816-03-01              27.426                          1.793  Bangkok
19949  1816-04-01              28.349                          3.011  Bangkok
19950  1816-05-01              28.781                          1.980  Bangkok
19951  1816-06-01              27.197                          1.823  Bangkok
19952  1816-07-01              25.728                          1.414  Bangkok
19953  1816-08-01              26.446                          1.061  Bangkok
19954  1816-09-01              25.593                          1.083  Bangkok
19955  1816-10-01              23.402                          4.323  Bangkok
19956  1816-11-01              23.736                          5.054  Bangkok
19957  1816-12-01              22.951                          1.968  Bangkok
19958  1817-01-01              23.990                          3.597  Bangkok
19959  1817-02-01              26.786                          2.047  Bangkok
19960  1817-03-01              27.898                          1.822  Bangkok
19961  1817-04-01              29.126                          1.800  Bangkok
19962  1817-05-01              27.386                          1.924  Bangkok
19963  1817-06-01              26.324                          1.427  Bangkok
19964  1817-07-01              26.028                          1.363  Bangkok
19965  1817-08-01              27.284                          1.465  Bangkok
19966  1817-09-01              24.424                          2.110  Bangkok
19967  1817-10-01              24.204                          2.225  Bangkok
19968  1817-11-01              24.610                          2.107  Bangkok
19969  1817-12-01              21.927                          2.400  Bangkok
19970  1818-01-01              23.961                          2.896  Bangkok
19971  1818-02-01              24.721                          1.749  Bangkok
19972  1818-03-01              28.755                          1.610  Bangkok
19973  1818-04-01              30.407                          4.081  Bangkok
19974  1818-05-01              29.230                          2.636  Bangkok
19975  1818-06-01              28.676                          3.061  Bangkok
19976  1818-07-01              26.661                          2.238  Bangkok
19977  1818-08-01              26.930                          1.137  Bangkok
...           ...                 ...                            ...      ...
22289  2011-04-01              28.915                          0.299  Bangkok
22290  2011-05-01              29.260                          0.245  Bangkok
22291  2011-06-01              28.760                          0.418  Bangkok
22292  2011-07-01              28.277                          0.516  Bangkok
22293  2011-08-01              28.157                          0.401  Bangkok
22294  2011-09-01              27.870                          0.434  Bangkok
22295  2011-10-01              27.317                          0.179  Bangkok
22296  2011-11-01              27.505                          0.404  Bangkok
22297  2011-12-01              25.021                          0.502  Bangkok
22298  2012-01-01              26.862                          0.513  Bangkok
22299  2012-02-01              28.208                          0.345  Bangkok
22300  2012-03-01              29.739                          0.198  Bangkok
22301  2012-04-01              30.435                          0.372  Bangkok
22302  2012-05-01              29.637                          0.306  Bangkok
22303  2012-06-01              29.130                          0.223  Bangkok
22304  2012-07-01              28.383                          0.364  Bangkok
22305  2012-08-01              28.461                          0.395  Bangkok
22306  2012-09-01              27.935                          0.279  Bangkok
22307  2012-10-01              27.994                          0.306  Bangkok
22308  2012-11-01              27.807                          0.445  Bangkok
22309  2012-12-01              27.215                          0.388  Bangkok
22310  2013-01-01              26.355                          0.458  Bangkok
22311  2013-02-01              28.648                          0.433  Bangkok
22312  2013-03-01              29.940                          0.424  Bangkok
22313  2013-04-01              30.731                          0.517  Bangkok
22314  2013-05-01              30.927                          0.504  Bangkok
22315  2013-06-01              28.771                          0.451  Bangkok
22316  2013-07-01              28.155                          0.308  Bangkok
22317  2013-08-01              28.351                          0.458  Bangkok
22318  2013-09-01                 NaN                            NaN  Bangkok

        Country Latitude Longitude
19948  Thailand   13.66N    99.91E
19949  Thailand   13.66N    99.91E
19950  Thailand   13.66N    99.91E
19951  Thailand   13.66N    99.91E
19952  Thailand   13.66N    99.91E
19953  Thailand   13.66N    99.91E
19954  Thailand   13.66N    99.91E
19955  Thailand   13.66N    99.91E
19956  Thailand   13.66N    99.91E
19957  Thailand   13.66N    99.91E
19958  Thailand   13.66N    99.91E
19959  Thailand   13.66N    99.91E
19960  Thailand   13.66N    99.91E
19961  Thailand   13.66N    99.91E
19962  Thailand   13.66N    99.91E
19963  Thailand   13.66N    99.91E
19964  Thailand   13.66N    99.91E
19965  Thailand   13.66N    99.91E
19966  Thailand   13.66N    99.91E
19967  Thailand   13.66N    99.91E
19968  Thailand   13.66N    99.91E
19969  Thailand   13.66N    99.91E
19970  Thailand   13.66N    99.91E
19971  Thailand   13.66N    99.91E
19972  Thailand   13.66N    99.91E
19973  Thailand   13.66N    99.91E
19974  Thailand   13.66N    99.91E
19975  Thailand   13.66N    99.91E
19976  Thailand   13.66N    99.91E
19977  Thailand   13.66N    99.91E
...         ...      ...       ...
22289  Thailand   13.66N    99.91E
22290  Thailand   13.66N    99.91E
22291  Thailand   13.66N    99.91E
22292  Thailand   13.66N    99.91E
22293  Thailand   13.66N    99.91E
22294  Thailand   13.66N    99.91E
22295  Thailand   13.66N    99.91E
22296  Thailand   13.66N    99.91E
22297  Thailand   13.66N    99.91E
22298  Thailand   13.66N    99.91E
22299  Thailand   13.66N    99.91E
22300  Thailand   13.66N    99.91E
22301  Thailand   13.66N    99.91E
22302  Thailand   13.66N    99.91E
22303  Thailand   13.66N    99.91E
22304  Thailand   13.66N    99.91E
22305  Thailand   13.66N    99.91E
22306  Thailand   13.66N    99.91E
22307  Thailand   13.66N    99.91E
22308  Thailand   13.66N    99.91E
22309  Thailand   13.66N    99.91E
22310  Thailand   13.66N    99.91E
22311  Thailand   13.66N    99.91E
22312  Thailand   13.66N    99.91E
22313  Thailand   13.66N    99.91E
22314  Thailand   13.66N    99.91E
22315  Thailand   13.66N    99.91E
22316  Thailand   13.66N    99.91E
22317  Thailand   13.66N    99.91E
22318  Thailand   13.66N    99.91E

[2371 rows x 7 columns]
Turkey
               dt  AverageTemperature  AverageTemperatureUncertainty    City  \
11893  1755-01-01              -3.657                          4.084  Ankara
11894  1755-02-01              -2.453                          3.712  Ankara
11895  1755-03-01               4.458                          3.421  Ankara
11896  1755-04-01                 NaN                            NaN  Ankara
11897  1755-05-01                 NaN                            NaN  Ankara
11898  1755-06-01              21.018                          2.593  Ankara
11899  1755-07-01              22.099                          1.963  Ankara
11900  1755-08-01              20.793                          2.475  Ankara
11901  1755-09-01              17.085                          1.891  Ankara
11902  1755-10-01              11.088                          4.733  Ankara
11903  1755-11-01               6.144                          4.715  Ankara
11904  1755-12-01              -0.341                          5.175  Ankara
11905  1756-01-01               0.224                          3.897  Ankara
11906  1756-02-01               3.787                          3.450  Ankara
11907  1756-03-01               5.095                          4.711  Ankara
11908  1756-04-01              11.791                          2.349  Ankara
11909  1756-05-01              16.613                          4.059  Ankara
11910  1756-06-01              20.433                          2.512  Ankara
11911  1756-07-01              21.761                          1.996  Ankara
11912  1756-08-01              20.667                          5.640  Ankara
11913  1756-09-01              18.072                          2.605  Ankara
11914  1756-10-01              10.276                          2.743  Ankara
11915  1756-11-01               4.317                          3.210  Ankara
11916  1756-12-01              -1.097                          2.687  Ankara
11917  1757-01-01              -3.895                          2.778  Ankara
11918  1757-02-01               2.123                          3.484  Ankara
11919  1757-03-01               5.331                          3.139  Ankara
11920  1757-04-01              10.037                          4.180  Ankara
11921  1757-05-01              16.072                          2.794  Ankara
11922  1757-06-01              22.752                          2.732  Ankara
...           ...                 ...                            ...     ...
96593  2011-04-01              14.186                          0.252   Izmir
96594  2011-05-01              18.957                          0.172   Izmir
96595  2011-06-01              23.886                          0.337   Izmir
96596  2011-07-01              27.044                          0.580   Izmir
96597  2011-08-01              26.490                          0.287   Izmir
96598  2011-09-01              24.727                          0.386   Izmir
96599  2011-10-01              17.251                          0.279   Izmir
96600  2011-11-01              12.627                          0.672   Izmir
96601  2011-12-01              12.179                          0.478   Izmir
96602  2012-01-01               8.353                          0.333   Izmir
96603  2012-02-01               9.108                          0.275   Izmir
96604  2012-03-01              11.909                          0.236   Izmir
96605  2012-04-01              16.628                          0.328   Izmir
96606  2012-05-01              19.718                          0.483   Izmir
96607  2012-06-01              25.367                          1.025   Izmir
96608  2012-07-01              28.952                          0.906   Izmir
96609  2012-08-01              27.962                          0.632   Izmir
96610  2012-09-01              24.374                          0.632   Izmir
96611  2012-10-01              21.292                          0.574   Izmir
96612  2012-11-01              17.107                          0.560   Izmir
96613  2012-12-01              11.677                          0.707   Izmir
96614  2013-01-01              11.065                          0.646   Izmir
96615  2013-02-01              12.137                          0.517   Izmir
96616  2013-03-01              13.846                          0.504   Izmir
96617  2013-04-01              16.643                          0.337   Izmir
96618  2013-05-01              21.723                          0.407   Izmir
96619  2013-06-01              24.416                          0.589   Izmir
96620  2013-07-01              26.451                          0.277   Izmir
96621  2013-08-01              27.430                          0.220   Izmir
96622  2013-09-01                 NaN                            NaN   Izmir

      Country Latitude Longitude
11893  Turkey   39.38N    33.29E
11894  Turkey   39.38N    33.29E
11895  Turkey   39.38N    33.29E
11896  Turkey   39.38N    33.29E
11897  Turkey   39.38N    33.29E
11898  Turkey   39.38N    33.29E
11899  Turkey   39.38N    33.29E
11900  Turkey   39.38N    33.29E
11901  Turkey   39.38N    33.29E
11902  Turkey   39.38N    33.29E
11903  Turkey   39.38N    33.29E
11904  Turkey   39.38N    33.29E
11905  Turkey   39.38N    33.29E
11906  Turkey   39.38N    33.29E
11907  Turkey   39.38N    33.29E
11908  Turkey   39.38N    33.29E
11909  Turkey   39.38N    33.29E
11910  Turkey   39.38N    33.29E
11911  Turkey   39.38N    33.29E
11912  Turkey   39.38N    33.29E
11913  Turkey   39.38N    33.29E
11914  Turkey   39.38N    33.29E

               dt  AverageTemperature  AverageTemperatureUncertainty  \
83484  1825-01-01              25.741                          2.275
83485  1825-02-01              25.610                          1.441
83486  1825-03-01              27.060                          1.960
83487  1825-04-01              28.660                          2.139
83488  1825-05-01              28.448                          1.304
83489  1825-06-01              28.725                          1.015
83490  1825-07-01              28.239                          2.255
83491  1825-08-01              27.427                          2.038
83492  1825-09-01              26.834                          1.612
83493  1825-10-01              26.183                          1.875
83494  1825-11-01              26.893                          1.812
83495  1825-12-01              25.537                          1.486
83496  1826-01-01                 NaN                            NaN
83497  1826-02-01                 NaN                            NaN
83498  1826-03-01                 NaN                            NaN
83499  1826-04-01                 NaN                            NaN
83500  1826-05-01                 NaN                            NaN
83501  1826-06-01                 NaN                            NaN
83502  1826-07-01                 NaN                            NaN
83503  1826-08-01                 NaN                            NaN
83504  1826-09-01                 NaN                            NaN
83505  1826-10-01                 NaN                            NaN
83506  1826-11-01                 NaN                            NaN
83507  1826-12-01                 NaN                            NaN
83508  1827-01-01                 NaN                            NaN
83509  1827-02-01                 NaN                            NaN
83510  1827-03-01                 NaN                            NaN
83511  1827-04-01                 NaN                            NaN
83512  1827-05-01                 NaN                            NaN
83513  1827-06-01                 NaN                            NaN
...           ...                 ...                            ...
85719  2011-04-01              27.888                          0.327
85720  2011-05-01              29.005                          0.480
85721  2011-06-01              28.591                          0.524
85722  2011-07-01              28.275                          0.606
85723  2011-08-01              28.510                          0.261
85724  2011-09-01              27.995                          0.377
85725  2011-10-01              27.855                          0.450
85726  2011-11-01              27.937                          0.190
85727  2011-12-01              26.474                          0.306
85728  2012-01-01              26.637                          0.300
85729  2012-02-01              27.186                          0.251
85730  2012-03-01              28.338                          0.175
85731  2012-04-01              28.623                          0.672
85732  2012-05-01              28.929                          0.586
85733  2012-06-01              29.055                          0.637
85734  2012-07-01              28.641                          0.706
85735  2012-08-01              28.910                          0.801
85736  2012-09-01              28.118                          0.495
85737  2012-10-01              27.948                          0.438
85738  2012-11-01              28.477                          0.398
85739  2012-12-01              28.123                          0.554
85740  2013-01-01              26.597                          0.298
85741  2013-02-01              27.586                          0.465
85742  2013-03-01              28.731                          0.488
85743  2013-04-01              29.360                          0.778
85744  2013-05-01              29.688                          0.342
85745  2013-06-01              28.939                          0.301
85746  2013-07-01              28.425                          0.787
85747  2013-08-01              28.314                          0.275
85748  2013-09-01                 NaN                            NaN

                   City  Country Latitude Longitude
83484  Ho Chi Minh City  Vietnam   10.45N   107.18E
83485  Ho Chi Minh City  Vietnam   10.45N   107.18E
83486  Ho Chi Minh City  Vietnam   10.45N   107.18E
83487  Ho Chi Minh City  Vietnam   10.45N   107.18E
83488  Ho Chi Minh City  Vietnam   10.45N   107.18E
83489  Ho Chi Minh City  Vietnam   10.45N   107.18E
83490  Ho Chi Minh City  Vietnam   10.45N   107.18E
83491  Ho Chi Minh City  Vietnam   10.45N   107.18E
83492  Ho Chi Minh City  Vietnam   10.45N   107.18E
83493  Ho Chi Minh City  Vietnam   10.45N   107.18E
83494  Ho Chi Minh City  Vietnam   10.45N   107.18E
83495  Ho Chi Minh City  Vietnam   10.45N   107.18E
83496  Ho Chi Minh City  Vietnam   10.45N   107.18E
83497  Ho Chi Minh City  Vietnam   10.45N   107.18E
83498  Ho Chi Minh City  Vietnam   10.45N   107.18E
83499  Ho Chi Minh City  Vietnam   10.45N   107.18E
83500  Ho Chi Minh City  Vietnam   10.45N   107.18E
83501  Ho Chi Minh City  Vietnam   10.45N   107.18E
83502  Ho Chi Minh City  Vietnam   10.45N   107.18E
83503  Ho Chi Minh City  Vietnam   10.45N   107.18E
83504  Ho Chi Minh City  Vietnam   10.45N   107.18E
83505  Ho Chi Minh City  Vietnam   10.45N   107.18E
83506  Ho Chi Minh City  Vietnam   10.45N   107.18E
83507  Ho Chi Minh City  Vietnam   10.45N   107.18E
83508  Ho Chi Minh City  Vietnam   10.45N   107.18E
83509  Ho Chi Minh City  Vietnam   10.45N   107.18E
83510  Ho Chi Minh City  Vietnam   10.45N   107.18E
83511  Ho Chi Minh City  Vietnam   10.45N   107.18E
83512  Ho Chi Minh City  Vietnam   10.45N   107.18E
83513  Ho Chi Minh City  Vietnam   10.45N   107.18E
...                 ...      ...      ...       ...
85719  Ho Chi Minh City  Vietnam   10.45N   107.18E
85720  Ho Chi Minh City  Vietnam   10.45N   107.18E
85721  Ho Chi Minh City  Vietnam   10.45N   107.18E
85722  Ho Chi Minh City  Vietnam   10.45N   107.18E
85723  Ho Chi Minh City  Vietnam   10.45N   107.18E
85724  Ho Chi Minh City  Vietnam   10.45N   107.18E
85725  Ho Chi Minh City  Vietnam   10.45N   107.18E
85726  Ho Chi Minh City  Vietnam   10.45N   107.18E
85727  Ho Chi Minh City  Vietnam   10.45N   107.18E
85728  Ho Chi Minh City  Vietnam   10.45N   107.18E
85729  Ho Chi Minh City  Vietnam   10.45N   107.18E
85730  Ho Chi Minh City  Vietnam   10.45N   107.18E
85731  Ho Chi Minh City  Vietnam   10.45N   107.18E
85732  Ho Chi Minh City  Vietnam   10.45N   107.18E
85733  Ho Chi Minh City  Vietnam   10.45N   107.18E
85734  Ho Chi Minh City  Vietnam   10.45N   107.18E
85735  Ho Chi Minh City  Vietnam   10.45N   107.18E
85736  Ho Chi Minh City  Vietnam   10.45N   107.18E
85737  Ho Chi Minh City  Vietnam   10.45N   107.18E
85738  Ho Chi Minh City  Vietnam   10.45N   107.18E
85739  Ho Chi Minh City  Vietnam   10.45N   107.18E
85740  Ho Chi Minh City  Vietnam   10.45N   107.18E
85741  Ho Chi Minh City  Vietnam   10.45N   107.18E
85742  Ho Chi Minh City  Vietnam   10.45N   107.18E
85743  Ho Chi Minh City  Vietnam   10.45N   107.18E
85744  Ho Chi Minh City  Vietnam   10.45N   107.18E
85745  Ho Chi Minh City  Vietnam   10.45N   107.18E
85746  Ho Chi Minh City  Vietnam   10.45N   107.18E
85747  Ho Chi Minh City  Vietnam   10.45N   107.18E
85748  Ho Chi Minh City  Vietnam   10.45N   107.18E

[2265 rows x 7 columns]
Zimbabwe
               dt  AverageTemperature  AverageTemperatureUncertainty    City  \
79201  1850-01-01              20.699                          1.552  Harare
79202  1850-02-01              22.193                          1.629  Harare
79203  1850-03-01              21.394                          2.176  Harare
79204  1850-04-01              19.097                          1.848  Harare
79205  1850-05-01              16.412                          1.568  Harare
79206  1850-06-01              15.099                          1.543  Harare
79207  1850-07-01              15.132                          1.510  Harare
79208  1850-08-01              17.499                          1.648  Harare
79209  1850-09-01              20.415                          1.609  Harare
79210  1850-10-01              22.104                          1.689  Harare
79211  1850-11-01              22.016                          1.842  Harare
79212  1850-12-01                 NaN                            NaN  Harare
79213  1851-01-01                 NaN                            NaN  Harare
79214  1851-02-01                 NaN                            NaN  Harare
79215  1851-03-01                 NaN                            NaN  Harare
79216  1851-04-01                 NaN                            NaN  Harare
79217  1851-05-01                 NaN                            NaN  Harare
79218  1851-06-01                 NaN                            NaN  Harare
79219  1851-07-01                 NaN                            NaN  Harare
79220  1851-08-01                 NaN                            NaN  Harare
79221  1851-09-01                 NaN                            NaN  Harare
79222  1851-10-01                 NaN                            NaN  Harare
79223  1851-11-01                 NaN                            NaN  Harare
79224  1851-12-01                 NaN                            NaN  Harare
79225  1852-01-01                 NaN                            NaN  Harare
79226  1852-02-01                 NaN                            NaN  Harare
79227  1852-03-01                 NaN                            NaN  Harare
79228  1852-04-01                 NaN                            NaN  Harare
79229  1852-05-01                 NaN                            NaN  Harare
79230  1852-06-01                 NaN                            NaN  Harare
...           ...                 ...                            ...     ...
81136  2011-04-01              21.151                          0.541  Harare
81137  2011-05-01              19.022                          0.421  Harare
81138  2011-06-01              16.512                          0.667  Harare
81139  2011-07-01              15.315                          0.479  Harare
81140  2011-08-01              17.287                          0.350  Harare
81141  2011-09-01              22.377                          0.938  Harare
81142  2011-10-01              24.353                          0.493  Harare
81143  2011-11-01              24.380                          0.337  Harare
81144  2011-12-01              22.857                          0.501  Harare
81145  2012-01-01              22.334                          0.270  Harare
81146  2012-02-01              22.943                          0.278  Harare
81147  2012-03-01              22.254                          0.565  Harare
81148  2012-04-01              19.129                          0.605  Harare
81149  2012-05-01              18.853                          0.308  Harare
81150  2012-06-01              16.119                          0.491  Harare
81151  2012-07-01              15.406                          0.819  Harare
81152  2012-08-01              18.191                          1.231  Harare
81153  2012-09-01              22.206                          0.779  Harare
81154  2012-10-01              22.692                          0.646  Harare
81155  2012-11-01              23.474                          0.463  Harare
81156  2012-12-01              22.679                          0.806  Harare
81157  2013-01-01              22.235                          1.143  Harare
81158  2013-02-01              22.737                          1.136  Harare
81159  2013-03-01              22.051                          0.489  Harare
81160  2013-04-01              20.180                          0.480  Harare
81161  2013-05-01              18.298                          1.117  Harare
81162  2013-06-01              17.020                          0.519  Harare
81163  2013-07-01              16.299                          0.510  Harare
81164  2013-08-01              19.232                          0.808  Harare
81165  2013-09-01                 NaN                            NaN  Harare

        Country Latitude Longitude
79201  Zimbabwe   18.48S    30.42E
79202  Zimbabwe   18.48S    30.42E
79203  Zimbabwe   18.48S    30.42E
79204  Zimbabwe   18.48S    30.42E
79205  Zimbabwe   18.48S    30.42E
79206  Zimbabwe   18.48S    30.42E
79207  Zimbabwe   18.48S    30.42E
79208  Zimbabwe   18.48S    30.42E
79209  Zimbabwe   18.48S    30.42E
79210  Zimbabwe   18.48S    30.42E
79211  Zimbabwe   18.48S    30.42E
79212  Zimbabwe   18.48S    30.42E
79213  Zimbabwe   18.48S    30.42E
79214  Zimbabwe   18.48S    30.42E
79215  Zimbabwe   18.48S    30.42E
79216  Zimbabwe   18.48S    30.42E
79217  Zimbabwe   18.48S    30.42E
79218  Zimbabwe   18.48S    30.42E
79219  Zimbabwe   18.48S    30.42E
79220  Zimbabwe   18.48S    30.42E
79221  Zimbabwe   18.48S    30.42E
79222  Zimbabwe   18.48S    30.42E
79223  Zimbabwe   18.48S    30.42E
79224  Zimbabwe   18.48S    30.42E
79225  Zimbabwe   18.48S    30.42E
79226  Zimbabwe   18.48S    30.42E
79227  Zimbabwe   18.48S    30.42E
79228  Zimbabwe   18.48S    30.42E
79229  Zimbabwe   18.48S    30.42E
79230  Zimbabwe   18.48S    30.42E
...         ...      ...       ...
81136  Zimbabwe   18.48S    30.42E
81137  Zimbabwe   18.48S    30.42E
81138  Zimbabwe   18.48S    30.42E
81139  Zimbabwe   18.48S    30.42E
81140  Zimbabwe   18.48S    30.42E
81141  Zimbabwe   18.48S    30.42E
81142  Zimbabwe   18.48S    30.42E
81143  Zimbabwe   18.48S    30.42E
81144  Zimbabwe   18.48S    30.42E
81145  Zimbabwe   18.48S    30.42E
81146  Zimbabwe   18.48S    30.42E
81147  Zimbabwe   18.48S    30.42E
81148  Zimbabwe   18.48S    30.42E
81149  Zimbabwe   18.48S    30.42E
81150  Zimbabwe   18.48S    30.42E
81151  Zimbabwe   18.48S    30.42E
81152  Zimbabwe   18.48S    30.42E
81153  Zimbabwe   18.48S    30.42E
81154  Zimbabwe   18.48S    30.42E
81155  Zimbabwe   18.48S    30.42E
81156  Zimbabwe   18.48S    30.42E
81157  Zimbabwe   18.48S    30.42E
81158  Zimbabwe   18.48S    30.42E
81159  Zimbabwe   18.48S    30.42E
81160  Zimbabwe   18.48S    30.42E
81161  Zimbabwe   18.48S    30.42E
81162  Zimbabwe   18.48S    30.42E
81163  Zimbabwe   18.48S    30.42E
81164  Zimbabwe   18.48S    30.42E
81165  Zimbabwe   18.48S    30.42E

[1965 rows x 7 columns]

In [13]:
for (k1 ,k2), group in df.groupby(['City', 'Country']):
    print k1
    print k2
    print group
    break

Abidjan
Côte D'Ivoire
              dt  AverageTemperature  AverageTemperatureUncertainty     City  \
0     1849-01-01              26.704                          1.435  Abidjan
1     1849-02-01              27.434                          1.362  Abidjan
2     1849-03-01              28.101                          1.612  Abidjan
3     1849-04-01              26.140                          1.387  Abidjan
4     1849-05-01              25.427                          1.200  Abidjan
5     1849-06-01              24.844                          1.402  Abidjan
6     1849-07-01              24.058                          1.254  Abidjan
7     1849-08-01              23.576                          1.265  Abidjan
8     1849-09-01              23.662                          1.226  Abidjan
9     1849-10-01              25.263                          1.175  Abidjan
10    1849-11-01              26.332                          1.507  Abidjan
11    1849-12-01              25.450                          1.838  Abidjan
12    1850-01-01              25.803                          1.943  Abidjan
13    1850-02-01              27.890                          1.430  Abidjan
14    1850-03-01              27.852                          2.173  Abidjan
15    1850-04-01              26.547                          1.662  Abidjan
16    1850-05-01              25.379                          1.355  Abidjan
17    1850-06-01              24.903                          1.178  Abidjan
18    1850-07-01              24.040                          1.301  Abidjan
19    1850-08-01              23.758                          1.282  Abidjan
20    1850-09-01              24.000                          1.220  Abidjan
21    1850-10-01              24.491                          1.178  Abidjan
22    1850-11-01              25.542                          1.719  Abidjan
23    1850-12-01              26.014                          1.603  Abidjan
24    1851-01-01              26.789                          1.249  Abidjan
25    1851-02-01              27.363                          1.218  Abidjan
26    1851-03-01              27.181                          1.428  Abidjan
27    1851-04-01              26.604                          1.654  Abidjan
28    1851-05-01              26.212                          1.195  Abidjan
29    1851-06-01              24.898                          1.329  Abidjan
...          ...                 ...                            ...      ...
1947  2011-04-01              28.754                          0.400  Abidjan
1948  2011-05-01              27.809                          0.376  Abidjan
1949  2011-06-01              26.427                          0.347  Abidjan
1950  2011-07-01              25.302                          0.255  Abidjan
1951  2011-08-01              24.824                          0.305  Abidjan
1952  2011-09-01              25.405                          0.198  Abidjan
1953  2011-10-01              26.388                          0.237  Abidjan
1954  2011-11-01              27.531                          0.285  Abidjan
1955  2011-12-01              27.194                          0.345  Abidjan
1956  2012-01-01              27.317                          0.440  Abidjan
1957  2012-02-01              27.697                          0.329  Abidjan
1958  2012-03-01              28.887                          0.213  Abidjan
1959  2012-04-01              28.025                          0.395  Abidjan
1960  2012-05-01              27.056                          0.347  Abidjan
1961  2012-06-01              26.101                          0.388  Abidjan
1962  2012-07-01              24.989                          0.461  Abidjan
1963  2012-08-01              24.657                          0.321  Abidjan
1964  2012-09-01              25.793                          0.401  Abidjan
1965  2012-10-01              26.511                          1.526  Abidjan
1966  2012-11-01              27.386                          0.394  Abidjan
1967  2012-12-01              26.777                          0.528  Abidjan
1968  2013-01-01              27.751                          0.856  Abidjan
1969  2013-02-01              29.021                          0.467  Abidjan
1970  2013-03-01              29.129                          0.306  Abidjan
1971  2013-04-01              28.626                          0.219  Abidjan
1972  2013-05-01              27.652                          0.160  Abidjan
1973  2013-06-01              26.157                          0.245  Abidjan
1974  2013-07-01              24.951                          0.221  Abidjan
1975  2013-08-01              24.541                          0.372  Abidjan
1976  2013-09-01                 NaN                            NaN  Abidjan

            Country Latitude Longitude
0     Côte D'Ivoire    5.63N     3.23W
1     Côte D'Ivoire    5.63N     3.23W
2     Côte D'Ivoire    5.63N     3.23W
3     Côte D'Ivoire    5.63N     3.23W
4     Côte D'Ivoire    5.63N     3.23W
5     Côte D'Ivoire    5.63N     3.23W
6     Côte D'Ivoire    5.63N     3.23W
7     Côte D'Ivoire    5.63N     3.23W
8     Côte D'Ivoire    5.63N     3.23W
9     Côte D'Ivoire    5.63N     3.23W
10    Côte D'Ivoire    5.63N     3.23W
11    Côte D'Ivoire    5.63N     3.23W
12    Côte D'Ivoire    5.63N     3.23W
13    Côte D'Ivoire    5.63N     3.23W
14    Côte D'Ivoire    5.63N     3.23W
15    Côte D'Ivoire    5.63N     3.23W
16    Côte D'Ivoire    5.63N     3.23W
17    Côte D'Ivoire    5.63N     3.23W
18    Côte D'Ivoire    5.63N     3.23W
19    Côte D'Ivoire    5.63N     3.23W
20    Côte D'Ivoire    5.63N     3.23W
21    Côte D'Ivoire    5.63N     3.23W
22    Côte D'Ivoire    5.63N     3.23W
23    Côte D'Ivoire    5.63N     3.23W
24    Côte D'Ivoire    5.63N     3.23W
25    Côte D'Ivoire    5.63N     3.23W
26    Côte D'Ivoire    5.63N     3.23W
27    Côte D'Ivoire    5.63N     3.23W
28    Côte D'Ivoire    5.63N     3.23W
29    Côte D'Ivoire    5.63N     3.23W
...             ...      ...       ...
1947  Côte D'Ivoire    5.63N     3.23W
1948  Côte D'Ivoire    5.63N     3.23W
1949  Côte D'Ivoire    5.63N     3.23W
1950  Côte D'Ivoire    5.63N     3.23W
1951  Côte D'Ivoire    5.63N     3.23W
1952  Côte D'Ivoire    5.63N     3.23W
1953  Côte D'Ivoire    5.63N     3.23W
1954  Côte D'Ivoire    5.63N     3.23W
1955  Côte D'Ivoire    5.63N     3.23W
1956  Côte D'Ivoire    5.63N     3.23W
1957  Côte D'Ivoire    5.63N     3.23W
1958  Côte D'Ivoire    5.63N     3.23W
1959  Côte D'Ivoire    5.63N     3.23W
1960  Côte D'Ivoire    5.63N     3.23W
1961  Côte D'Ivoire    5.63N     3.23W
1962  Côte D'Ivoire    5.63N     3.23W
1963  Côte D'Ivoire    5.63N     3.23W
1964  Côte D'Ivoire    5.63N     3.23W
1965  Côte D'Ivoire    5.63N     3.23W
1966  Côte D'Ivoire    5.63N     3.23W
1967  Côte D'Ivoire    5.63N     3.23W
1968  Côte D'Ivoire    5.63N     3.23W
1969  Côte D'Ivoire    5.63N     3.23W
1970  Côte D'Ivoire    5.63N     3.23W
1971  Côte D'Ivoire    5.63N     3.23W
1972  Côte D'Ivoire    5.63N     3.23W
1973  Côte D'Ivoire    5.63N     3.23W
1974  Côte D'Ivoire    5.63N     3.23W
1975  Côte D'Ivoire    5.63N     3.23W
1976  Côte D'Ivoire    5.63N     3.23W

[1977 rows x 7 columns]

In [15]:
pieces = dict(list(df.groupby('City')))

In [17]:
pieces.keys()

['Kinshasa',
 'Kiev',
 'Madras',
 'Paris',
 'Fortaleza',
 'Bangkok',
 'Santiago',
 'Addis Abeba',
 'Delhi',
 'Baghdad',
 'Taipei',
 'Ahmadabad',
 'Pune',
 'Nagpur',
 'Rome',
 'Tangshan',
 'Surat',
 'Ho Chi Minh City',
 'Mogadishu',
 'Harbin',
 'Casablanca',
 'Alexandria',
 'Kanpur',
 'Cairo',
 'Shenyang',
 'Abidjan',
 'London',
 'Bombay',
 'Harare',
 'Sydney',
 'Dakar',
 'Seoul',
 'Singapore',
 'Moscow',
 'Guangzhou',
 'Berlin',
 'Los Angeles',
 'Bangalore',
 'Karachi',
 'Ibadan',
 'Cape Town',
 'Taiyuan',
 'Kano',
 'Lakhnau',
 'Madrid',
 'Xian',
 'Rio De Janeiro',
 'Dar Es Salaam',
 'Istanbul',
 'Mashhad',
 'Aleppo',
 'Manila',
 'Lahore',
 'Luanda',
 'Durban',
 'Jaipur',
 'Faisalabad',
 'Gizeh',
 'Rangoon',
 'New Delhi',
 'Nagoya',
 'Wuhan',
 'Calcutta',
 'Nairobi',
 'Montreal',
 'Umm Durman',
 'Mexico',
 'Saint Petersburg',
 'New York',
 'Lima',
 'Belo Horizonte',
 'Toronto',
 'Surabaya',
 'Chicago',
 'Tianjin',
 'Shanghai',
 'Bogot\xc3\xa1',
 'Kabul',
 'Cali',
 'Jiddah',
 'S\xc3\xa3o Paulo',
 'Bras\xc3\xadlia',
 'Tokyo',
 'Changchun',
 'Ankara',
 'Chongqing',
 'Dhaka',
 'Salvador',
 'Jakarta',
 'Melbourne',
 'Peking',
 'Hyderabad',
 'Dalian',
 'Chengdu',
 'Riyadh',
 'Jinan',
 'Nanjing',
 'Santo Domingo',
 'Lagos',
 'Izmir']

In [19]:
df.dtypes

dt                                object
AverageTemperature               float64
AverageTemperatureUncertainty    float64
City                              object
Country                           object
Latitude                          object
Longitude                         object
dtype: object